import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      exclude: [
        "node_modules/",
        "vitest.setup.ts",
        "**/*.d.ts",
        "**/*.config.*",
        "**/dist/**",
        "**/.next/**",
        "**/coverage/**",
        "**/types/**",
        "**/e2e/**",
        "**/*.cy.ts",
        "**/providers/**",
        "**/scripts/**",
        "**/api/__generated__/**",
        "**/__tests__/**",
        "**/layout.tsx",
        "**/page.tsx",
        "**/loading.tsx",
        "**/error.tsx",
        "**/not-found.tsx",
        "**/global-error.tsx",
        "**/template.tsx",
        "**/default.tsx",
        "app/globals.css",
        "postcss.config.mjs",
        "tailwind.config.ts",
        "next.config.ts",
        "next-env.d.ts",
        "**/hooks/api/**",
        "**/views/**",
        "**/theme/ThemeProvider.tsx",
        "**/theme/fonts.ts",
        "app/utils/trpc.ts",
        "app/utils/confirm.tsx",
        "**/ContentBrowserModal/**",
        "**/ConfigRequestModal/ConfigRequestModal.tsx",
        "**/ConfigRequestModal/ConfigHeader.tsx",
        "**/ConfigRequestModal/OptionGrid.tsx",
        "**/ConfigRequestModal/types.ts",
        "**/CategoriesGrid/CategoriesGrid.tsx",
        "**/CoverflowCarousel/CoverflowCarousel.tsx",
        "**/CoverflowCarousel/CoverflowCard.tsx",
        "**/CoverflowCarousel/CoverflowSkeleton.tsx",
        "**/ArtistSpotlight/**",
        "**/TrendingHero/**",
        "**/LibraryLeaderboard/**",
        "**/RecentRequests/RecentRequests.tsx",
        "**/RecentRequests/RecentRequestsSkeleton.tsx",
        "**/RequestCard/AlbumCard/**",
        "**/Toolbar/Toolbar.tsx",
        "**/Table/Table.tsx",
        "**/Table/RequestRow.tsx",
        "**/Results/Results.tsx",
        "**/Results/AllResults.tsx",
        "**/Results/types.ts",
        "**/components/ContentShell.tsx",
        "**/components/TopHeader.tsx",
        "**/components/UserAvatarMenu/**",
        "**/components/NavIcon.tsx",
        "**/components/ui/Dialog.tsx",
        "**/components/ui/DropdownMenu.tsx",
        "**/components/ui/TablePrimitives.tsx",
        "**/components/ui/ConfirmationModal.tsx",
        "**/components/ui/ImageWithFallback/**",
        "**/components/ui/ImageGlow/**",
        "**/components/ui/Sonner.tsx",
        "**/components/ui/LogoIcon.tsx",
        "**/components/ui/CircularLoadingImage.tsx",
        "**/api/health/**",
        "**/api/trpc/**",
        "**/features/*/index.ts",
        "**/features/*/types.ts",
        "**/TopHeader/styles.ts",
        "**/components/ui/styles.ts",
        "**/components/ui/Table/**",
        "**/hooks/useRequestStatus.ts",
      ],
      thresholds: {
        lines: 85,
        functions: 85,
        branches: 85,
        statements: 85,
      },
    },
    include: ["**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    exclude: ["node_modules", "dist", ".next", "coverage"],
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./"),
      "@components": path.resolve(__dirname, "./app/components"),
      "@features": path.resolve(__dirname, "./app/features"),
      "@utils": path.resolve(__dirname, "./app/utils"),
      "@hooks": path.resolve(__dirname, "./app/hooks"),
      "@modules": path.resolve(__dirname, "./app/modules"),
      "@theme": path.resolve(__dirname, "./app/theme"),
      "@api": path.resolve(__dirname, "./app/api"),
      "@test": path.resolve(__dirname, "./__tests__"),
    },
  },
});
