import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    coverage: {
      provider: "v8",
      all: true,
      include: ["app/**/*.{ts,tsx}"],
      reporter: ["text", "json", "json-summary", "html", "lcov"],
      exclude: [
        "**/*.d.ts",
        "**/api/__generated__/**",
        "**/__tests__/**",
        "**/*.{test,spec}.{ts,tsx}",
        "**/e2e/**",
        "**/*.cy.ts",
        "**/scripts/**",
        "**/*.config.*",
        "**/coverage/**",
        "**/.next/**",
        "**/node_modules/**",
        "app/**/types.ts",
        "app/**/*.types.ts",
        "app/**/index.ts",
        "app/**/layout.tsx",
        "app/**/page.tsx",
        "app/**/loading.tsx",
        "app/**/error.tsx",
        "app/**/not-found.tsx",
        "app/**/global-error.tsx",
        "app/**/template.tsx",
        "app/**/default.tsx",
        "app/**/providers/**",
        "app/theme/ThemeProvider.tsx",
        "app/theme/fonts.ts",
        "app/utils/trpc.ts",
        "app/hooks/api/index.ts",
        "app/hooks/api/queries/*.ts",
        "app/hooks/api/queries/spotify/**",
        "app/hooks/api/queries/portability/**",
        "app/hooks/api/mutations/**",
        "app/api/health/**",
        "app/api/v1/trpc/**",
        "app/api/v1/types/**",
        "app/api/v1/logs/archive/**",
      ],
      thresholds: {
        lines: 0,
        functions: 0,
        branches: 0,
        statements: 0,
      },
    },
    include: ["**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    exclude: ["node_modules", "dist", ".next", "coverage"],
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./"),
      "@components": path.resolve(__dirname, "./app/components"),
      "@features": path.resolve(__dirname, "./app/features"),
      "@utils": path.resolve(__dirname, "./app/utils"),
      "@hooks": path.resolve(__dirname, "./app/hooks"),
      "@modules": path.resolve(__dirname, "./app/modules"),
      "@locale": path.resolve(__dirname, "./app/modules/i18n"),
      "@theme": path.resolve(__dirname, "./app/theme"),
      "@api": path.resolve(__dirname, "./app/api"),
      "@test": path.resolve(__dirname, "./__tests__"),
    },
  },
});
