import type { MusicImage, MusicPlaylist, MusicTrack } from "@api/__generated__/types";
import type { LbPlaylistKind } from "@features/discovery-integrations/types";

import { EMPTY_REASON_LABELS } from "./constants";
import type { DiscoveryMix, FeedCandidate, LbKindMeta } from "./types";

function albumImagesOf(candidate: FeedCandidate): MusicImage[] {
  return candidate.albumImage ? [{ url: candidate.albumImage, width: null, height: null }] : [];
}

export function synthesizeTrack(candidate: FeedCandidate): MusicTrack {
  const images = albumImagesOf(candidate);
  return {
    type: "track",
    id: candidate.catalogTrackId,
    title: candidate.title,
    artist: candidate.artist,
    artists: [{ id: `${candidate.catalogTrackId}:artist`, name: candidate.artist }],
    album: { id: candidate.albumExternalId, name: candidate.albumName, images },
    duration_ms: candidate.durationMs,
    track_number: candidate.trackNumber,
    disc_number: candidate.discNumber,
    isrc: candidate.isrc,
    explicit: candidate.explicit,
    popularity: candidate.popularity,
    preview_url: null,
    images,
  };
}

export function formatHumanDate(date: Date): string {
  const month = date.toLocaleString("en-US", { month: "short" });
  return `${month} ${date.getDate()} ${date.getFullYear()}`;
}

export function synthesizePlaylist(mix: DiscoveryMix, meta: LbKindMeta, tracks: MusicTrack[]): MusicPlaylist {
  const stamp = mix.generatedAt ?? "unsynced";
  const dateLabel = mix.generatedAt ? formatHumanDate(new Date(mix.generatedAt)) : "no sync";
  const cover = tracks[0]?.album.images[0]?.url ?? null;
  return {
    type: "playlist",
    id: `discovery:listenbrainz:${mix.kind}:${stamp}`,
    name: `${meta.label} (${dateLabel})`,
    description: `Generated by Discovery · listenbrainz:${mix.kind}`,
    images: cover ? [{ url: cover, width: null, height: null }] : [],
    owner: { id: "discovery", name: "ListenBrainz" },
    total_tracks: tracks.length,
    tracks: [],
  };
}

export function formatFreshness(generatedAt: string | undefined, kind: LbPlaylistKind, now: number): string | null {
  if (!generatedAt) return null;
  const date = new Date(generatedAt);
  const diffDays = Math.floor((now - date.getTime()) / 86_400_000);
  if (diffDays < 0) return null;

  if (kind === "cf-recommendations") {
    return diffDays === 0 ? "Synced today" : `Synced ${diffDays}d ago`;
  }
  if (kind === "daily-jams") {
    return diffDays === 0 ? "Updated today" : `Updated ${diffDays}d ago`;
  }
  if (diffDays === 0) return "Updated today";
  if (diffDays < 7) return `Updated ${date.toLocaleDateString("en-US", { weekday: "short" })}`;
  return `Updated ${diffDays}d ago`;
}

export function describeEmptyReason(mix: DiscoveryMix): string {
  if (mix.status === "none") return "Waiting for first sync";
  return EMPTY_REASON_LABELS[mix.emptyReason ?? ""] ?? "Feed empty";
}

export function tileGradient(seed: string): string {
  let h = 0;
  for (const ch of seed) h = (h * 31 + ch.charCodeAt(0)) % 360;
  const h2 = (h + 38) % 360;
  return `linear-gradient(140deg, oklch(0.62 0.18 ${h}deg), oklch(0.42 0.16 ${h2}deg))`;
}
