import type { ParseKeys } from "i18next";

import i18n from "@locale";
import type { MusicImage, MusicPlaylist, MusicTrack } from "@api/__generated__/types";
import type { LbPlaylistKind } from "@features/discovery-integrations/types";

import { EMPTY_REASON_FALLBACK_KEY, EMPTY_REASON_KEYS, WAITING_FIRST_SYNC_KEY } from "./constants";
import type { DiscoveryMix, DiscoveryMixesEmptyReason, FeedCandidate, LbKindMeta } from "./types";

const EMPTY_TEXT_KEYS: Record<DiscoveryMixesEmptyReason, ParseKeys<"discover">> = {
  error: "mixes.empty.error",
  disabled: "mixes.empty.disabled",
  "no-username": "mixes.empty.noUsername",
  "no-kinds": "mixes.empty.noKinds",
};

export function emptyTextKey(reason: DiscoveryMixesEmptyReason): ParseKeys<"discover"> {
  return EMPTY_TEXT_KEYS[reason];
}

function albumImagesOf(candidate: FeedCandidate): MusicImage[] {
  return candidate.albumImage ? [{ url: candidate.albumImage, width: null, height: null }] : [];
}

export function synthesizeTrack(candidate: FeedCandidate): MusicTrack {
  const images = albumImagesOf(candidate);
  return {
    type: "track",
    id: candidate.catalogTrackId,
    title: candidate.title,
    artist: candidate.artist,
    artists: [{ id: `${candidate.catalogTrackId}:artist`, name: candidate.artist }],
    album: { id: candidate.albumExternalId, name: candidate.albumName, images },
    duration_ms: candidate.durationMs,
    track_number: candidate.trackNumber,
    disc_number: candidate.discNumber,
    isrc: candidate.isrc,
    explicit: candidate.explicit,
    popularity: candidate.popularity,
    preview_url: null,
    images,
  };
}

export function formatHumanDate(date: Date): string {
  const month = date.toLocaleString("en-US", { month: "short" });
  return `${month} ${date.getDate()} ${date.getFullYear()}`;
}

export function synthesizePlaylist(
  mix: DiscoveryMix,
  meta: LbKindMeta,
  tracks: MusicTrack[],
  customName?: string
): MusicPlaylist {
  const stamp = mix.generatedAt ?? "unsynced";
  const dateLabel = mix.generatedAt ? formatHumanDate(new Date(mix.generatedAt)) : "no sync";
  const cover = tracks[0]?.album.images[0]?.url ?? null;
  const label = customName?.trim() || meta.label;
  return {
    type: "playlist",
    id: `discovery:listenbrainz:${mix.kind}:${stamp}`,
    name: `${label} (${dateLabel})`,
    description: `Generated by Discovery · listenbrainz:${mix.kind}`,
    images: cover ? [{ url: cover, width: null, height: null }] : [],
    owner: { id: "discovery", name: "ListenBrainz" },
    total_tracks: tracks.length,
    tracks: [],
  };
}

export function formatFreshness(generatedAt: string | undefined, kind: LbPlaylistKind, now: number): string | null {
  if (!generatedAt) return null;
  const date = new Date(generatedAt);
  const diffDays = Math.floor((now - date.getTime()) / 86_400_000);
  if (diffDays < 0) return null;

  if (kind === "cf-recommendations") {
    return diffDays === 0
      ? i18n.t("discover:mixes.freshness.syncedToday")
      : i18n.t("discover:mixes.freshness.syncedDaysAgo", { count: diffDays });
  }
  if (kind === "daily-jams") {
    return diffDays === 0
      ? i18n.t("discover:mixes.freshness.updatedToday")
      : i18n.t("discover:mixes.freshness.updatedDaysAgo", { count: diffDays });
  }
  if (diffDays === 0) return i18n.t("discover:mixes.freshness.updatedToday");
  if (diffDays < 7) {
    const weekday = date.toLocaleDateString(i18n.language, { weekday: "short" });
    return i18n.t("discover:mixes.freshness.updatedWeekday", { weekday });
  }
  return i18n.t("discover:mixes.freshness.updatedDaysAgo", { count: diffDays });
}

export function describeEmptyReason(mix: DiscoveryMix): string {
  if (mix.status === "none") return i18n.t(`discover:${WAITING_FIRST_SYNC_KEY}`);
  const key = EMPTY_REASON_KEYS[mix.emptyReason ?? ""] ?? EMPTY_REASON_FALLBACK_KEY;
  return i18n.t(`discover:${key}`);
}

export function tileGradient(seed: string): string {
  let h = 0;
  for (const ch of seed) h = (h * 31 + ch.charCodeAt(0)) % 360;
  const h2 = (h + 38) % 360;
  return `linear-gradient(140deg, oklch(0.62 0.18 ${h}deg), oklch(0.42 0.16 ${h2}deg))`;
}
