/**
 * Auto-generated types from Synthseek Backend
 * DO NOT EDIT - Generated by npm run generate
 * Generated at: 2026-06-29T10:43:30.241Z
 */

import { z } from "zod";

// ============================================================================
// ENUMS
// ============================================================================

export const RequestStatus = z.enum([
  "queued",
  "searching",
  "pending_download",
  "downloading",
  "paused",
  "pending_import",
  "importing",
  "in_progress",
  "syncing_plex",
  "partially_complete",
  "complete",
  "failed",
  "cancelled",
  "delegated",
]);
export type RequestStatus = z.infer<typeof RequestStatus>;

export const ContentType = z.enum(["track", "album", "playlist", "artist"]);
export type ContentType = z.infer<typeof ContentType>;

export const SearchIntent = z.enum(["specific", "genre", "mood", "inconclusive"]);
export type SearchIntent = z.infer<typeof SearchIntent>;

export const RequestFormat = z.enum(["mp3", "flac", "aac", "m4a", "ogg", "wav", "opus"]);
export type RequestFormat = z.infer<typeof RequestFormat>;

export const RequestMatchingMode = z.enum(["strict", "flexible"]);
export type RequestMatchingMode = z.infer<typeof RequestMatchingMode>;

export const Role = z.enum(["admin", "member"]);
export type Role = z.infer<typeof Role>;

export const ReclaimOutcome = z.enum(["created", "already_complete", "already_in_progress", "requeued"]);
export type ReclaimOutcome = z.infer<typeof ReclaimOutcome>;

export const FailureReason = z.enum([
  "not_found",
  "import_rejected",
  "wrong_file",
  "p2p_failed",
  "download_failed",
  "other",
]);
export type FailureReason = z.infer<typeof FailureReason>;

export const AppErrorCode = z.enum([
  "AUTHENTICATION_REQUIRED",
  "ADMIN_ROLE_REQUIRED",
  "INVALID_CREDENTIALS",
  "CURRENT_PASSWORD_INCORRECT",
  "ACCOUNT_HAS_NO_PASSWORD",
  "SETUP_ALREADY_COMPLETED",
  "PLEX_USER_NOT_LINKED",
  "CAN_ONLY_MODIFY_OWN_REQUESTS",
  "EMAIL_MANAGED_BY_PLEX",
  "PLEX_ALREADY_LINKED",
  "PASSWORD_REQUIRED_BEFORE_UNLINK",
  "OWNER_MUST_REMAIN_ADMIN",
  "AT_LEAST_ONE_ADMIN_REQUIRED",
  "CANNOT_DELETE_OWN_ACCOUNT",
  "OWNER_CANNOT_BE_DELETED",
  "NO_OWNER_ACCOUNT",
  "USER_NOT_FOUND",
  "EMAIL_TAKEN",
  "USERNAME_TAKEN",
  "PLEX_NOT_CONFIGURED",
  "PLEX_UNREACHABLE",
  "ALBUM_NOT_FOUND",
  "PLAYLIST_NOT_FOUND",
  "TRACK_NOT_FOUND",
  "COLLECTION_NOT_FOUND",
  "REQUEST_NOT_FOUND",
  "API_KEY_NOT_FOUND",
  "OAUTH_REQUEST_NOT_FOUND",
  "DOWNLOAD_FAILED",
  "BATCH_DOWNLOAD_FAILED",
  "INVALID_CONTENT_TYPES",
  "LIBRARY_SOURCE_NOT_CONFIGURED",
  "LIBRARY_SOURCE_CALLBACK_FAILED",
  "LIBRARY_SOURCE_REAUTH_REQUIRED",
  "LIDARR_CONNECTION_FAILED",
  "LIDARR_PROFILES_FAILED",
  "LIDARR_SEARCH_FAILED",
  "LIDARR_ADD_ARTIST_FAILED",
  "LIDARR_CHECK_ARTIST_FAILED",
  "LIDARR_ARTIST_EXISTS",
  "LIDARR_ALBUM_NOT_IN_CATALOG",
  "LIDARR_ARTIST_NOT_IN_CATALOG",
  "LIDARR_HANDOFF_FAILED",
  "VALUE_ALREADY_IN_USE",
  "PLAYLIST_SYNCED_NOT_EDITABLE",
  "PLAYLIST_TRACK_IN_FLIGHT",
]);
export type AppErrorCode = z.infer<typeof AppErrorCode>;

// ============================================================================
// SCHEMAS
// ============================================================================

export const PublicUser = z.object({
  id: z.string(),
  email: z.string().email(),
  username: z.string(),
  avatar_url: z.string().nullable(),
  role: Role,
  language: z.string(),
  plex_username: z.string().nullable(),
  plexLinked: z.boolean(),
  hasPassword: z.boolean(),
  created_at: z.coerce.date(),
});
export type PublicUser = z.infer<typeof PublicUser>;

export const AlbumSchema = z.object({
  id: z.string(),
  external_id: z.string(),
  name: z.string(),
  artist: z.string(),
  album_art: z.string().nullable(),
  user_id: z.string(),
  release_date: z.string(),
  total_tracks: z.number().int(),
  completed_tracks: z.number().int(),
  status: RequestStatus.default("queued"),
  genres: z.string().nullable(),
  upc: z.string().nullable(),
  delegated_to: z.string().nullable(),
  source_provider: z.string().nullable(),
  source_id: z.string().nullable(),
  auto_imported: z.boolean().default(false),
  requested: z.boolean().default(false),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
  requested_at: z.coerce.date(),
});
export type Album = z.infer<typeof AlbumSchema>;

export const TrackRequestSchema = z.object({
  id: z.string(),
  slskd_request_id: z.string(),
  external_id: z.string(),
  user_id: z.string(),
  title: z.string(),
  artist: z.string(),
  request_type: ContentType.default("track"),
  isrc: z.string().nullable(),
  mbid: z.string().nullable(),
  track_number: z.number().int(),
  disc_number: z.number().int().default(1),
  duration_ms: z.number().int(),
  status: RequestStatus.default("queued"),
  progress: z.number().int(),
  priority: z.number().int(),
  bitrate: z.number().int().default(320),
  format: RequestFormat.default("mp3"),
  format_matching: RequestMatchingMode.default("flexible"),
  bitrate_matching: RequestMatchingMode.default("flexible"),
  album_id: z.string(),
  error: z.string().nullable(),
  explicit: z.boolean(),
  source: z.string().default("deezer"),
  failure_reason: FailureReason.nullable(),
  downloaded_file: z.string().nullable(),
  created_at: z.coerce.date(),
  completed_at: z.coerce.date().nullable(),
  updated_at: z.coerce.date(),
});
export type TrackRequest = z.infer<typeof TrackRequestSchema>;

// ============================================================================
// RELATION SCHEMAS
// ============================================================================

export const RequestWithTracksSchema = AlbumSchema.extend({
  tracks: z.array(TrackRequestSchema),
  contentType: ContentType,
  plex_playlist_id: z.string().nullable(),
  sync_enabled: z.boolean().optional(),
  duplicateCount: z.number().int(),
  requestedBy: PublicUser,
});
export type RequestWithTracks = z.infer<typeof RequestWithTracksSchema>;

export const TrackRequestWithAlbumSchema = TrackRequestSchema.extend({
  Album: AlbumSchema,
});
export type TrackRequestWithAlbum = z.infer<typeof TrackRequestWithAlbumSchema>;

// ============================================================================
// SUBSCRIPTION EVENTS
// ============================================================================

export enum SubscriptionEventType {
  TrackUpdate = "TrackUpdate",
  AlbumUpdate = "AlbumUpdate",
  PlaylistUpdate = "PlaylistUpdate",
  PlaylistPlexCreated = "PlaylistPlexCreated",
  PlexSyncAllProgress = "PlexSyncAllProgress",
  VersionUpdate = "VersionUpdate",
  SettingsUpdate = "SettingsUpdate",
  PortabilityProgress = "PortabilityProgress",
  LibraryImportProgress = "LibraryImportProgress",
}

export interface CorrelatedEvent {
  correlationId?: string | null;
}

export interface TrackUpdatePayload extends CorrelatedEvent {
  eventType: SubscriptionEventType.TrackUpdate;
  requestId: string;
  status: RequestStatus;
  progress?: number;
  error?: string;
  message: string;
  persisted?: boolean;
  failureReason?: FailureReason | null;
  downloadedFile?: string | null;
  metadata?: {
    artist?: string;
    track?: string;
    filename?: string;
    username?: string;
    id?: string;
  };
}

export interface AlbumUpdatePayload extends CorrelatedEvent {
  eventType: SubscriptionEventType.AlbumUpdate;
  albumId: string;
  status: RequestStatus;
  completedTracks: number;
  totalTracks: number;
}

export interface PlaylistUpdatePayload extends CorrelatedEvent {
  eventType: SubscriptionEventType.PlaylistUpdate;
  playlistId: string;
  status: RequestStatus;
  completedTracks: number;
  totalTracks: number;
  populatePhase?: "complete" | "partial" | "failed";
}

export interface PlaylistPlexCreatedPayload extends CorrelatedEvent {
  eventType: SubscriptionEventType.PlaylistPlexCreated;
  playlistId: string;
  plexPlaylistId: string;
}

export interface PlexSyncAllProgressPayload extends CorrelatedEvent {
  eventType: SubscriptionEventType.PlexSyncAllProgress;
  phase: "start" | "progress" | "complete";
  synced: number;
  total: number;
  failed?: number;
  items?: { id: string; name: string }[];
  current?: { id: string; ok: boolean };
}

export interface VersionUpdatePayload {
  eventType: SubscriptionEventType.VersionUpdate;
  currentVersion: string;
  latestVersion: string;
  message: string;
}

export interface SettingsUpdatePayload extends CorrelatedEvent {
  eventType: SubscriptionEventType.SettingsUpdate;
  changedKey: string;
}

export interface PortabilityProgressPayload extends CorrelatedEvent {
  eventType: SubscriptionEventType.PortabilityProgress;
  jobId: string;
  phase: "matching" | "resolving-mbid";
  processed: number;
  total: number;
  collection?: { key: string; state: "importing" | "done" | "failed" };
}

export interface LibraryImportProgressPayload extends CorrelatedEvent {
  eventType: SubscriptionEventType.LibraryImportProgress;
  jobId: string;
  provider: string;
  phase: "start" | "progress" | "complete";
  item?: {
    key: string;
    state: "importing" | "done" | "failed" | "skipped";
    reason?: "notInLibrary" | "noMatchableTracks" | "sourceHasNoTracks" | "importError";
  };
  imported: number;
  failed: number;
  total: number;
}

export type SubscriptionEvent =
  | TrackUpdatePayload
  | AlbumUpdatePayload
  | PlaylistUpdatePayload
  | PlaylistPlexCreatedPayload
  | PlexSyncAllProgressPayload
  | VersionUpdatePayload
  | SettingsUpdatePayload
  | PortabilityProgressPayload
  | LibraryImportProgressPayload;

// ============================================================================
// CONSTANTS
// ============================================================================

export const ACTIVE_STATUSES = [
  RequestStatus.enum.queued,
  RequestStatus.enum.in_progress,
  RequestStatus.enum.searching,
  RequestStatus.enum.pending_download,
  RequestStatus.enum.downloading,
  RequestStatus.enum.paused,
  RequestStatus.enum.pending_import,
  RequestStatus.enum.importing,
  RequestStatus.enum.syncing_plex,
] as const;

export const RESOLVED_STATUSES = [
  RequestStatus.enum.complete,
  RequestStatus.enum.partially_complete,
  RequestStatus.enum.delegated,
] as const;

export const UNRESOLVED_STATUSES = [
  RequestStatus.enum.failed,
  RequestStatus.enum.cancelled,
] as const;

export const FORMAT_OPTIONS = [
  { value: RequestFormat.enum.mp3, label: "MP3", desc: "Universal" },
  { value: RequestFormat.enum.flac, label: "FLAC", desc: "Lossless" },
  { value: RequestFormat.enum.aac, label: "AAC", desc: "High Quality" },
  { value: RequestFormat.enum.m4a, label: "M4A", desc: "Apple Lossless" },
  { value: RequestFormat.enum.ogg, label: "OGG", desc: "Open Source" },
  { value: RequestFormat.enum.wav, label: "WAV", desc: "Uncompressed" },
  { value: RequestFormat.enum.opus, label: "OPUS", desc: "Efficient Streaming" },
] as const;

// ============================================================================
// MUSIC TYPES (provider-agnostic)
// ============================================================================

export interface MusicImage {
  url: string;
  width: number | null;
  height: number | null;
}

export interface MusicArtistRef {
  id: string;
  name: string;
}

export interface MusicTrack {
  type: "track";
  id: string;
  title: string;
  artist: string;
  artists: MusicArtistRef[];
  album: { id: string; name: string; images: MusicImage[] };
  duration_ms: number;
  track_number: number;
  disc_number: number;
  isrc: string | null;
  explicit: boolean;
  popularity: number | null;
  preview_url: string | null;
  images: MusicImage[];
}

export interface MusicAlbum {
  type: "album";
  id: string;
  name: string;
  artist: string;
  artists: MusicArtistRef[];
  images: MusicImage[];
  release_date: string;
  total_tracks: number;
  genres: string[];
  label: string | null;
  upc: string | null;
  tracks: MusicTrack[];
}

export interface MusicArtist {
  type: "artist";
  id: string;
  name: string;
  images: MusicImage[];
  genres: string[];
  followers: number | null;
}

export interface MusicPlaylist {
  type: "playlist";
  id: string;
  name: string;
  description: string | null;
  images: MusicImage[];
  owner: { id: string; name: string };
  total_tracks: number;
  tracks: MusicPlaylistTrack[];
}

export interface MusicPlaylistTrack {
  added_at: string | null;
  track: MusicTrack;
}

export interface MusicGenre {
  id: string;
  name: string;
  images: MusicImage[];
}

export interface PagingResult<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

export type MusicItem = MusicTrack | MusicAlbum | MusicArtist | MusicPlaylist;

export interface SearchResults {
  tracks?: PagingResult<MusicTrack>;
  albums?: PagingResult<MusicAlbum>;
  artists?: PagingResult<MusicArtist>;
  playlists?: PagingResult<MusicPlaylist>;
}

export interface ClassificationResult {
  intent: SearchIntent;
  confidence: number;
  genreId?: string;
  genreName?: string;
  source: "genre-rules" | "learned-pattern" | "post-search" | "default";
}

export type FilterType = ContentType | "all";

export interface FilterTab {
  value: FilterType;
  label: string;
}

export interface TrendingResult {
  tracks: { track: MusicTrack; addedAt: string }[];
  source: { name: string; totalResults: number };
}


export interface ArtistSpotlightItem {
  artist: MusicArtist;
  latestAlbum: MusicAlbum | null;
}

export interface ArtistSpotlightResponse {
  artists: ArtistSpotlightItem[];
}

// ============================================================================
// SINGLE DOWNLOAD RESULT
// ============================================================================

export interface SingleDownloadResult {
  outcome: ReclaimOutcome;
  success: boolean;
  message: string;
  requestId: string;
  requestDbId: string;
  data: {
    artist: string;
    track: string;
    album: string;
    year: string;
    trackNumber: number;
    albumArt: string | null;
  };
  config: {
    bitrate: number;
    format: string;
    bitrateMatching: RequestMatchingMode;
    formatMatching: RequestMatchingMode;
  };
}

// ============================================================================
// LIDARR PROFILES (delegate modal)
// ============================================================================

export interface LidarrQualityItem {
  quality?: {
    id: number;
    name: string;
  };
  items: LidarrQualityItem[];
  allowed: boolean;
}

export interface LidarrQualityProfile {
  id: number;
  name: string;
  upgradeAllowed: boolean;
  cutoff: number;
  items: LidarrQualityItem[];
}

export interface LidarrAlbumType {
  albumType: {
    id: number;
    name: string;
  };
  allowed: boolean;
}

export interface LidarrReleaseStatus {
  releaseStatus: {
    id: number;
    name: string;
  };
  allowed: boolean;
}

export interface LidarrMetadataProfile {
  id: number;
  name: string;
  primaryAlbumTypes: LidarrAlbumType[];
  secondaryAlbumTypes: LidarrAlbumType[];
  releaseStatuses: LidarrReleaseStatus[];
}

export interface LidarrUnmappedFolder {
  name: string;
  path: string;
}

export interface LidarrRootFolder {
  id: number;
  path: string;
  accessible: boolean;
  freeSpace: number;
  unmappedFolders: LidarrUnmappedFolder[];
}


// ============================================================================
// TRPC ROUTER TYPE (auto-generated from tsc declaration output)
// ============================================================================

export declare const appRouter: import("@trpc/server").TRPCBuiltRouter<{
	ctx: Context;
	meta: object;
	errorShape: {
		data: {
			zodError: unknown | null;
			appCode: AppErrorCode | null;
			code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
			httpStatus: number;
			path?: string;
			stack?: string;
		};
		message: string;
		code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
	};
	transformer: true;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
	auth: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		me: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				id: string;
				email: string;
				username: string;
				avatar_url: string | null;
				role: "admin" | "member";
				language: string;
				plex_username: string | null;
				plexLinked: boolean;
				hasPassword: boolean;
				created_at: Date;
			} | null;
			meta: object;
		}>;
		setupRequired: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: boolean;
			meta: object;
		}>;
		setupBootstrap: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				email: string;
				username: string;
				password: string;
			};
			output: {
				id: string;
				email: string;
				username: string;
				avatar_url: string | null;
				role: "admin" | "member";
				language: string;
				plex_username: string | null;
				plexLinked: boolean;
				hasPassword: boolean;
				created_at: Date;
			};
			meta: object;
		}>;
		loginLocal: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				email: string;
				password: string;
			};
			output: {
				id: string;
				email: string;
				username: string;
				avatar_url: string | null;
				role: "admin" | "member";
				language: string;
				plex_username: string | null;
				plexLinked: boolean;
				hasPassword: boolean;
				created_at: Date;
			};
			meta: object;
		}>;
		logout: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				success: boolean;
			};
			meta: object;
		}>;
		updateProfile: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				username?: string | undefined;
				email?: string | undefined;
				avatar_url?: string | null | undefined;
				language?: "en" | "de" | "es" | "fr" | undefined;
			};
			output: {
				id: string;
				email: string;
				username: string;
				avatar_url: string | null;
				role: "admin" | "member";
				language: string;
				plex_username: string | null;
				plexLinked: boolean;
				hasPassword: boolean;
				created_at: Date;
			};
			meta: object;
		}>;
		changePassword: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				currentPassword: string;
				newPassword: string;
			};
			output: {
				success: boolean;
			};
			meta: object;
		}>;
		plexStart: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				pinId: string;
				authUrl: string;
			};
			meta: object;
		}>;
		plexComplete: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				pinId: string;
			};
			output: {
				status: "pending" | "authenticated";
				user: {
					id: string;
					email: string;
					username: string;
					avatar_url: string | null;
					role: "admin" | "member";
					language: string;
					plex_username: string | null;
					plexLinked: boolean;
					hasPassword: boolean;
					created_at: Date;
				} | null;
			};
			meta: object;
		}>;
		linkPlexStart: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				pinId: string;
				authUrl: string;
			};
			meta: object;
		}>;
		linkPlexComplete: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				pinId: string;
			};
			output: {
				status: "pending" | "linked";
				link: {
					plexLinked: boolean;
					plexUsername: string | null;
				} | null;
			};
			meta: object;
		}>;
		unlinkPlex: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				plexLinked: boolean;
				plexUsername: string | null;
			};
			meta: object;
		}>;
	}>>;
	users: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		list: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				id: string;
				email: string;
				username: string;
				avatar_url: string | null;
				role: "admin" | "member";
				language: string;
				plex_username: string | null;
				plexLinked: boolean;
				hasPassword: boolean;
				created_at: Date;
				requestCount: number;
				isOwner: boolean;
				isPlexUser: boolean;
			}[];
			meta: object;
		}>;
		create: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				email: string;
				username: string;
				password: string;
				role?: "admin" | "member" | undefined;
			};
			output: {
				id: string;
				email: string;
				username: string;
				avatar_url: string | null;
				role: "admin" | "member";
				language: string;
				plex_username: string | null;
				plexLinked: boolean;
				hasPassword: boolean;
				created_at: Date;
			};
			meta: object;
		}>;
		update: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: string;
				username?: string | undefined;
				email?: string | undefined;
				role?: "admin" | "member" | undefined;
				password?: string | undefined;
			};
			output: {
				id: string;
				email: string;
				username: string;
				avatar_url: string | null;
				role: "admin" | "member";
				language: string;
				plex_username: string | null;
				plexLinked: boolean;
				hasPassword: boolean;
				created_at: Date;
			};
			meta: object;
		}>;
		delete: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: string;
			};
			output: {
				success: boolean;
			};
			meta: object;
		}>;
		bulkUpdateRole: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				ids: string[];
				role: "admin" | "member";
			};
			output: {
				updated: number;
			};
			meta: object;
		}>;
		bulkDelete: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				ids: string[];
			};
			output: {
				deleted: number;
			};
			meta: object;
		}>;
		plexImportable: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				plexId: string;
				username: string;
				title: string;
				email: string;
				thumb: string | null;
				alreadyImported: boolean;
			}[];
			meta: object;
		}>;
		importPlex: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				plexUserIds: string[];
				role?: "admin" | "member" | undefined;
			};
			output: {
				imported: {
					id: string;
					email: string;
					username: string;
					avatar_url: string | null;
					role: "admin" | "member";
					language: string;
					plex_username: string | null;
					plexLinked: boolean;
					hasPassword: boolean;
					created_at: Date;
				}[];
				skipped: number;
			};
			meta: object;
		}>;
	}>>;
	requests: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		request: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				track: {
					external_id: string;
					artist: string;
					title: string;
					isrc: string | null;
					track_number: number;
					duration_ms: number;
					explicit: boolean;
					disc_number?: number | undefined;
				};
				config: {
					bitrate: {
						value: number;
						matching: "strict" | "flexible";
					};
					format: {
						value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
						matching: "strict" | "flexible";
					};
					minUploadSpeed?: number | undefined;
					requireFreeSlot?: boolean | undefined;
					sourceChain?: ("slskd" | "ytdlp")[] | undefined;
				};
				album_external_id: string;
			};
			output: SingleDownloadResult;
			meta: object;
		}>;
		batchRequest: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				name: string;
				external_id: string;
				artist: string;
				album_art: string | null;
				release_date: string;
				total_tracks: number;
				tracks: {
					external_id: string;
					artist: string;
					title: string;
					isrc: string | null;
					track_number: number;
					duration_ms: number;
					explicit: boolean;
					disc_number?: number | undefined;
				}[];
				config: {
					bitrate: {
						value: number;
						matching: "strict" | "flexible";
					};
					format: {
						value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
						matching: "strict" | "flexible";
					};
					minUploadSpeed?: number | undefined;
					requireFreeSlot?: boolean | undefined;
					sourceChain?: ("slskd" | "ytdlp")[] | undefined;
				};
				genres?: string[] | undefined;
				delegate?: {
					manager: "lidarr";
					rootFolderPath: string;
					qualityProfileId: number;
					metadataProfileId: number;
					monitor: "album" | "missing" | "all" | "future" | "none";
					tags?: string[] | undefined;
				} | undefined;
			};
			output: {
				outcome: "created" | "already_complete" | "already_in_progress" | "requeued";
				data: {
					id: string;
					external_id: string;
					name: string;
					artist: string;
					album_art: string | null;
					user_id: string;
					release_date: string;
					total_tracks: number;
					completed_tracks: number;
					status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
					genres: string | null;
					upc: string | null;
					delegated_to: string | null;
					source_provider: string | null;
					source_id: string | null;
					auto_imported: boolean;
					requested: boolean;
					created_at: Date;
					updated_at: Date;
					requested_at: Date;
					tracks: {
						id: string;
						slskd_request_id: string;
						external_id: string;
						user_id: string;
						title: string;
						artist: string;
						request_type: "artist" | "track" | "album" | "playlist";
						isrc: string | null;
						mbid: string | null;
						track_number: number;
						disc_number: number;
						duration_ms: number;
						status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
						progress: number;
						priority: number;
						bitrate: number;
						format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
						format_matching: "strict" | "flexible";
						bitrate_matching: "strict" | "flexible";
						min_upload_speed: number;
						require_free_slot: boolean;
						source_chain: string | null;
						album_id: string;
						error: string | null;
						explicit: boolean;
						source: string;
						failure_reason: "not_found" | "import_rejected" | "wrong_file" | "p2p_failed" | "download_failed" | "other" | null;
						downloaded_file: string | null;
						created_at: Date;
						completed_at: Date | null;
						updated_at: Date;
					}[];
					contentType: "artist" | "track" | "album" | "playlist";
					plex_playlist_id: string | null;
					duplicateCount: number;
					requestedBy: {
						id: string;
						email: string;
						username: string;
						avatar_url: string | null;
						role: "admin" | "member";
						language: string;
						plex_username: string | null;
						plexLinked: boolean;
						hasPassword: boolean;
						created_at: Date;
					};
					sync_enabled?: boolean | undefined;
				};
			};
			meta: object;
		}>;
		getStatus: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				requestId: string;
			};
			output: {
				success: boolean;
				status: {
					requestId: string;
					status: RequestStatus;
					progress: number;
					error: string | null;
				};
			};
			meta: object;
		}>;
		getAll: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				id: string;
				external_id: string;
				name: string;
				artist: string;
				album_art: string | null;
				user_id: string;
				release_date: string;
				total_tracks: number;
				completed_tracks: number;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
				genres: string | null;
				upc: string | null;
				delegated_to: string | null;
				source_provider: string | null;
				source_id: string | null;
				auto_imported: boolean;
				requested: boolean;
				created_at: Date;
				updated_at: Date;
				requested_at: Date;
				tracks: {
					id: string;
					slskd_request_id: string;
					external_id: string;
					user_id: string;
					title: string;
					artist: string;
					request_type: "artist" | "track" | "album" | "playlist";
					isrc: string | null;
					mbid: string | null;
					track_number: number;
					disc_number: number;
					duration_ms: number;
					status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
					progress: number;
					priority: number;
					bitrate: number;
					format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
					format_matching: "strict" | "flexible";
					bitrate_matching: "strict" | "flexible";
					min_upload_speed: number;
					require_free_slot: boolean;
					source_chain: string | null;
					album_id: string;
					error: string | null;
					explicit: boolean;
					source: string;
					failure_reason: "not_found" | "import_rejected" | "wrong_file" | "p2p_failed" | "download_failed" | "other" | null;
					downloaded_file: string | null;
					created_at: Date;
					completed_at: Date | null;
					updated_at: Date;
				}[];
				contentType: "artist" | "track" | "album" | "playlist";
				plex_playlist_id: string | null;
				duplicateCount: number;
				requestedBy: {
					id: string;
					email: string;
					username: string;
					avatar_url: string | null;
					role: "admin" | "member";
					language: string;
					plex_username: string | null;
					plexLinked: boolean;
					hasPassword: boolean;
					created_at: Date;
				};
				sync_enabled?: boolean | undefined;
			}[];
			meta: object;
		}>;
		createTrack: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				error: string | null;
				created_at: Date;
				updated_at: Date;
				user_id: string;
				external_id: string;
				artist: string;
				slskd_request_id: string;
				title: string;
				isrc: string | null;
				track_number: number;
				duration_ms: number;
				progress: number;
				min_upload_speed: number;
				require_free_slot: boolean;
				source_chain: string | null;
				album_id: string;
				explicit: boolean;
				failure_reason: "not_found" | "import_rejected" | "wrong_file" | "p2p_failed" | "download_failed" | "other" | null;
				downloaded_file: string | null;
				completed_at: Date | null;
				format?: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus" | undefined;
				status?: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated" | undefined;
				disc_number?: number | undefined;
				bitrate?: number | undefined;
				format_matching?: "strict" | "flexible" | undefined;
				bitrate_matching?: "strict" | "flexible" | undefined;
				source?: string | undefined;
			};
			output: {
				id: string;
				slskd_request_id: string;
				external_id: string;
				user_id: string;
				title: string;
				artist: string;
				request_type: "artist" | "track" | "album" | "playlist";
				isrc: string | null;
				mbid: string | null;
				track_number: number;
				disc_number: number;
				duration_ms: number;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
				progress: number;
				priority: number;
				bitrate: number;
				format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
				format_matching: "strict" | "flexible";
				bitrate_matching: "strict" | "flexible";
				min_upload_speed: number;
				require_free_slot: boolean;
				source_chain: string | null;
				album_id: string;
				error: string | null;
				explicit: boolean;
				source: string;
				failure_reason: "not_found" | "import_rejected" | "wrong_file" | "p2p_failed" | "download_failed" | "other" | null;
				downloaded_file: string | null;
				created_at: Date;
				completed_at: Date | null;
				updated_at: Date;
			};
			meta: object;
		}>;
		update: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: string;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
				progress?: number | undefined;
				error?: string | null | undefined;
				metadata?: Record<string, unknown> | undefined;
			};
			output: {
				id: string;
				slskd_request_id: string;
				external_id: string;
				user_id: string;
				title: string;
				artist: string;
				request_type: "artist" | "track" | "album" | "playlist";
				isrc: string | null;
				mbid: string | null;
				track_number: number;
				disc_number: number;
				duration_ms: number;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
				progress: number;
				priority: number;
				bitrate: number;
				format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
				format_matching: "strict" | "flexible";
				bitrate_matching: "strict" | "flexible";
				min_upload_speed: number;
				require_free_slot: boolean;
				source_chain: string | null;
				album_id: string;
				error: string | null;
				explicit: boolean;
				source: string;
				failure_reason: "not_found" | "import_rejected" | "wrong_file" | "p2p_failed" | "download_failed" | "other" | null;
				downloaded_file: string | null;
				created_at: Date;
				completed_at: Date | null;
				updated_at: Date;
			};
			meta: object;
		}>;
		delete: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: string;
			};
			output: {
				success: boolean;
				id?: string | undefined;
			};
			meta: object;
		}>;
		deleteAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				success: boolean;
				id?: string | undefined;
			};
			meta: object;
		}>;
		retryAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				message: string;
				retriedCount: number;
			};
			meta: object;
		}>;
		cancelAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				message: string;
				cancelledCount: number;
			};
			meta: object;
		}>;
		cancelTrack: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				trackId: string;
			};
			output: {
				success: boolean;
				trackId: string;
			};
			meta: object;
		}>;
		retryTrack: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				trackId: string;
			};
			output: {
				success: boolean;
				trackId: string;
			};
			meta: object;
		}>;
		retryTracks: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				trackIds: string[];
			};
			output: {
				requested: number;
				retried: number;
				skipped: {
					id: string;
					reason: "notFound" | "forbidden" | "notRetryable" | "retryError";
				}[];
			};
			meta: object;
		}>;
		prioritizeTrack: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				trackId: string;
			};
			output: {
				success: boolean;
				trackId: string;
			};
			meta: object;
		}>;
		prioritizeAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				success: boolean;
				albumId: string;
			};
			meta: object;
		}>;
		pauseAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				success: boolean;
				albumId: string;
				pausedCount: number;
			};
			meta: object;
		}>;
		resumeAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				success: boolean;
				albumId: string;
				resumedCount: number;
			};
			meta: object;
		}>;
		prioritizePlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				success: boolean;
				playlistId: string;
			};
			meta: object;
		}>;
		pausePlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				success: boolean;
				playlistId: string;
				pausedCount: number;
			};
			meta: object;
		}>;
		resumePlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				success: boolean;
				playlistId: string;
				resumedCount: number;
			};
			meta: object;
		}>;
		retryAllFailed: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				retried: number;
				failed: number;
			};
			meta: object;
		}>;
		pauseAll: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				success: boolean;
				pausedCount: number;
			};
			meta: object;
		}>;
		resumeAll: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				success: boolean;
				resumedCount: number;
			};
			meta: object;
		}>;
		getQueueState: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				isPaused: boolean;
			};
			meta: object;
		}>;
		deleteAll: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				deleted: number;
			};
			meta: object;
		}>;
		clearCompleted: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				count: number;
			};
			meta: object;
		}>;
		getLibrarySummary: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				completedTracks: number;
				completedAlbums: number;
				queuedTracks: number;
				totalDurationMs: number;
				topArtists: {
					artist: string;
					trackCount: number;
					image: string | null;
				}[];
				topGenres: {
					genre: string;
					albumCount: number;
					image: string | null;
				}[];
			};
			meta: object;
		}>;
		playlistRequest: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				external_id: string;
				name: string;
				owner: string;
				total_tracks: number;
				tracks: {
					external_id: string;
					artist: string;
					title: string;
					isrc: string | null;
					track_number: number;
					duration_ms: number;
					explicit: boolean;
					album_external_id: string;
					album_name: string;
					album_artist: string;
					disc_number?: number | undefined;
					album_image?: string | null | undefined;
				}[];
				config: {
					bitrate: {
						value: number;
						matching: "strict" | "flexible";
					};
					format: {
						value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
						matching: "strict" | "flexible";
					};
					minUploadSpeed?: number | undefined;
					requireFreeSlot?: boolean | undefined;
					sourceChain?: ("slskd" | "ytdlp")[] | undefined;
				};
				description?: string | null | undefined;
				image?: string | null | undefined;
			};
			output: CreatePlaylistRequestResult;
			meta: object;
		}>;
		deletePlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				success: boolean;
			};
			meta: object;
		}>;
		retryPlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				retriedCount: number;
			};
			meta: object;
		}>;
		cancelPlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				cancelledCount: number;
			};
			meta: object;
		}>;
		retryPlexPlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				success: boolean;
			};
			meta: object;
		}>;
		syncAllPlaylistsToPlex: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				started: boolean;
				running: boolean;
				synced: number;
				total: number;
			};
			meta: object;
		}>;
		getPlexSyncAllState: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				running: boolean;
				synced: number;
				total: number;
			};
			meta: object;
		}>;
		getPopulatingPlaylists: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				playlistId: string;
				name: string;
				totalTracks: number;
			}[];
			meta: object;
		}>;
	}>>;
	music: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		search: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				q: string;
				type?: string | undefined;
				limit?: number | undefined;
				offset?: number | undefined;
			};
			output: {
				success: boolean;
				results: SearchResults;
				classification: ClassificationResult;
			};
			meta: object;
		}>;
		getContent: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				type: "artist" | "track" | "album" | "playlist";
				id: string;
				include?: ("artist" | "track" | "album" | "playlist")[] | undefined;
			};
			output: {
				success: boolean;
				data: Record<string, unknown>;
			};
			meta: object;
		}>;
		getContents: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				parentType: "artist" | "track" | "album" | "playlist";
				parentId: string;
			};
			output: {
				success: boolean;
				content: MusicTrack[] | MusicPlaylistTrack[] | MusicAlbum[];
			};
			meta: object;
		}>;
		getTrendingTracks: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				success: boolean;
				data: TrendingResult;
			};
			meta: object;
		}>;
		getArtistSpotlight: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				countryName: string;
				limit?: number | undefined;
			};
			output: {
				success: boolean;
				data: {
					artists: ArtistSpotlightItem[];
				};
			};
			meta: object;
		}>;
		getArtistTopTracks: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				artistId: string;
				limit?: number | undefined;
			};
			output: {
				success: boolean;
				data: MusicTrack[];
			};
			meta: object;
		}>;
		getCategories: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				limit?: number | undefined;
				offset?: number | undefined;
			};
			output: {
				success: boolean;
				data: {
					items: MusicGenre[];
					total: number;
					limit: number;
					offset: number;
				};
			};
			meta: object;
		}>;
		getCategoryPlaylists: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				categoryId: string;
				categoryName: string;
				limit?: number | undefined;
				offset?: number | undefined;
			};
			output: {
				success: boolean;
				data: GenreContent;
			};
			meta: object;
		}>;
		getSimilarArtists: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				artistName: string;
				limit?: number | undefined;
			};
			output: {
				success: boolean;
				data: {
					id: string;
					name: string;
					match: number;
				}[];
			};
			meta: object;
		}>;
		importPlaylistFromUrl: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				url: string;
			};
			output: {
				success: boolean;
				data: ResolvedTrack[];
			};
			meta: object;
		}>;
		detectCountry: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				success: boolean;
				country: string;
			};
			meta: object;
		}>;
	}>>;
	playlists: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		rename: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
				name: string;
			};
			output: {
				id: string;
				name: string;
			};
			meta: object;
		}>;
		createLocal: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				name: string;
				trackIds: string[];
			};
			output: {
				id: string;
				name: string;
				sourceProvider: string | null;
				syncEnabled: boolean;
				totalTracks: number;
				completedTracks: number;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
			};
			meta: object;
		}>;
		addTracks: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
				trackIds: string[];
			};
			output: {
				id: string;
				name: string;
				sourceProvider: string | null;
				syncEnabled: boolean;
				totalTracks: number;
				completedTracks: number;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
			};
			meta: object;
		}>;
		removeTracks: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
				trackIds: string[];
			};
			output: {
				id: string;
				name: string;
				sourceProvider: string | null;
				syncEnabled: boolean;
				totalTracks: number;
				completedTracks: number;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
			};
			meta: object;
		}>;
		replaceTracks: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				trackIds: string[];
				id?: string | undefined;
				name?: string | undefined;
			};
			output: {
				id: string;
				name: string;
				sourceProvider: string | null;
				syncEnabled: boolean;
				totalTracks: number;
				completedTracks: number;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
			};
			meta: object;
		}>;
		setSync: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
				enabled: boolean;
			};
			output: {
				id: string;
				syncEnabled: boolean;
			};
			meta: object;
		}>;
	}>>;
	contentDetail: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		artistIdentity: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				deezerArtistId: string;
				artistName: string;
			};
			output: {
				deezerArtistId: string;
				image: string | null;
				mbid: string | null;
				wikidataQid: string | null;
				discogsArtistId: string | null;
				type: string | null;
				country: string | null;
				formedYear: number | null;
				realName: string | null;
				bornDate: string | null;
				bornPlace: string | null;
				members: string[];
				awards: {
					name: string;
					won: boolean;
				}[];
				socials: {
					instagram: string | null;
					youtube: string | null;
					appleMusic: string | null;
					spotify: string | null;
				};
			};
			meta: object;
		}>;
		artistStats: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				artistName: string;
				mbid?: string | undefined;
			};
			output: {
				listeners: number | null;
				scrobbles: number | null;
				lbListens: number | null;
				bio: string | null;
				genres: string[];
			};
			meta: object;
		}>;
		artistTopTracks: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				deezerArtistId: string;
			};
			output: {
				externalId: string;
				title: string;
				artist: string;
				durationMs: number;
				trackNumber: number;
				isrc: string | null;
				plays: number | null;
				inLibrary: boolean;
				requestId: string | null;
				slskd_request_id: string | null;
				status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated" | null;
				failureReason: "not_found" | "import_rejected" | "wrong_file" | "p2p_failed" | "download_failed" | "other" | null;
			}[];
			meta: object;
		}>;
		artistSimilar: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				artistName: string;
			};
			output: {
				deezerArtistId: string | null;
				name: string;
				match: number;
				image: string | null;
			}[];
			meta: object;
		}>;
		resolveArtist: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				name: string;
			};
			output: {
				deezerArtistId: string;
				name: string;
				image: string | null;
			} | null;
			meta: object;
		}>;
		artistDiscography: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				deezerArtistId: string;
			};
			output: {
				counts: {
					album: number;
					single: number;
					ep: number;
					live: number;
				};
				groups: {
					recordType: "album" | "live" | "compilation" | "ep" | "single";
					albums: {
						externalId: string;
						title: string;
						image: string | null;
						totalTracks: number;
						inLibrary: boolean;
						libraryTrackCount: number;
					}[];
				}[];
			};
			meta: object;
		}>;
		albumDetail: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				deezerAlbumId: string;
			};
			output: {
				externalId: string;
				title: string;
				artist: string;
				artistExternalId: string | null;
				genres: string[];
				cover: string | null;
				label: string | null;
				releaseDate: string | null;
				recordType: string | null;
				totalTracks: number;
				length: string | null;
				inLibrary: boolean;
				libraryTrackCount: number;
				tracks: {
					externalId: string;
					title: string;
					artist: string;
					durationMs: number;
					trackNumber: number;
					isrc: string | null;
					plays: number | null;
					inLibrary: boolean;
					requestId: string | null;
					slskd_request_id: string | null;
					status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated" | null;
					failureReason: "not_found" | "import_rejected" | "wrong_file" | "p2p_failed" | "download_failed" | "other" | null;
				}[];
			};
			meta: object;
		}>;
		albumStats: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				artistName: string;
				albumName: string;
				mbid?: string | undefined;
			};
			output: {
				listeners: number | null;
				scrobbles: number | null;
				lbListens: number | null;
				description: string | null;
			};
			meta: object;
		}>;
		albumCredits: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				deezerAlbumId: string;
				barcode?: string | undefined;
			};
			output: {
				producers: string[];
				studios: string[];
				engineers: string[];
				certification: string | null;
			};
			meta: object;
		}>;
		playlistDetail: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				id: string;
				name: string;
				cover: string | null;
				sourceProvider: string | null;
				syncEnabled: boolean;
				totalTracks: number;
				libraryTrackCount: number;
				tracks: {
					externalId: string;
					title: string;
					artist: string;
					durationMs: number;
					trackNumber: number;
					isrc: string | null;
					plays: number | null;
					inLibrary: boolean;
					requestId: string | null;
					slskd_request_id: string | null;
					status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated" | null;
					failureReason: "not_found" | "import_rejected" | "wrong_file" | "p2p_failed" | "download_failed" | "other" | null;
				}[];
			};
			meta: object;
		}>;
	}>>;
	portability: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		exportCollection: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				id: string;
				type: "album" | "playlist";
			};
			output: {
				playlist: {
					track: {
						title: string;
						location?: string | string[] | undefined;
						identifier?: string | string[] | undefined;
						creator?: string | null | undefined;
						album?: string | null | undefined;
						trackNum?: number | undefined;
						duration?: number | undefined;
						image?: string | null | undefined;
						annotation?: string | null | undefined;
						extension?: {
							"https://synthseek.app/jspf#track"?: {
								isrc?: string | null | undefined;
								mbid?: string | null | undefined;
								catalog?: Record<string, string> | undefined;
								disc_number?: number | undefined;
								explicit?: boolean | undefined;
							} | undefined;
						} | undefined;
					}[];
					title?: string | undefined;
					creator?: string | null | undefined;
					annotation?: string | null | undefined;
					info?: string | undefined;
					image?: string | null | undefined;
					identifier?: string | string[] | undefined;
					date?: string | undefined;
					extension?: {
						"https://synthseek.app/jspf#playlist"?: {
							collection_type?: "album" | "playlist" | undefined;
							config?: {
								bitrate: {
									value: number;
									matching: "strict" | "flexible";
								};
								format: {
									value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
									matching: "strict" | "flexible";
								};
								minUploadSpeed: number;
								requireFreeSlot: boolean;
								sourceChain?: ("slskd" | "ytdlp")[] | undefined;
							} | undefined;
						} | undefined;
					} | undefined;
				};
			};
			meta: object;
		}>;
		exportBundle: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				items: {
					id: string;
					type: "album" | "playlist";
				}[];
			};
			output: {
				synthseek_bundle: number;
				playlists: {
					playlist: {
						track: {
							title: string;
							location?: string | string[] | undefined;
							identifier?: string | string[] | undefined;
							creator?: string | null | undefined;
							album?: string | null | undefined;
							trackNum?: number | undefined;
							duration?: number | undefined;
							image?: string | null | undefined;
							annotation?: string | null | undefined;
							extension?: {
								"https://synthseek.app/jspf#track"?: {
									isrc?: string | null | undefined;
									mbid?: string | null | undefined;
									catalog?: Record<string, string> | undefined;
									disc_number?: number | undefined;
									explicit?: boolean | undefined;
								} | undefined;
							} | undefined;
						}[];
						title?: string | undefined;
						creator?: string | null | undefined;
						annotation?: string | null | undefined;
						info?: string | undefined;
						image?: string | null | undefined;
						identifier?: string | string[] | undefined;
						date?: string | undefined;
						extension?: {
							"https://synthseek.app/jspf#playlist"?: {
								collection_type?: "album" | "playlist" | undefined;
								config?: {
									bitrate: {
										value: number;
										matching: "strict" | "flexible";
									};
									format: {
										value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
										matching: "strict" | "flexible";
									};
									minUploadSpeed: number;
									requireFreeSlot: boolean;
									sourceChain?: ("slskd" | "ytdlp")[] | undefined;
								} | undefined;
							} | undefined;
						} | undefined;
					};
				}[];
				version?: number | undefined;
				exported_at?: string | undefined;
			};
			meta: object;
		}>;
		exportFullPortability: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: string;
				type: "album" | "playlist";
				jobId: string;
			};
			output: {
				playlist: {
					track: {
						title: string;
						location?: string | string[] | undefined;
						identifier?: string | string[] | undefined;
						creator?: string | null | undefined;
						album?: string | null | undefined;
						trackNum?: number | undefined;
						duration?: number | undefined;
						image?: string | null | undefined;
						annotation?: string | null | undefined;
						extension?: {
							"https://synthseek.app/jspf#track"?: {
								isrc?: string | null | undefined;
								mbid?: string | null | undefined;
								catalog?: Record<string, string> | undefined;
								disc_number?: number | undefined;
								explicit?: boolean | undefined;
							} | undefined;
						} | undefined;
					}[];
					title?: string | undefined;
					creator?: string | null | undefined;
					annotation?: string | null | undefined;
					info?: string | undefined;
					image?: string | null | undefined;
					identifier?: string | string[] | undefined;
					date?: string | undefined;
					extension?: {
						"https://synthseek.app/jspf#playlist"?: {
							collection_type?: "album" | "playlist" | undefined;
							config?: {
								bitrate: {
									value: number;
									matching: "strict" | "flexible";
								};
								format: {
									value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
									matching: "strict" | "flexible";
								};
								minUploadSpeed: number;
								requireFreeSlot: boolean;
								sourceChain?: ("slskd" | "ytdlp")[] | undefined;
							} | undefined;
						} | undefined;
					} | undefined;
				};
			};
			meta: object;
		}>;
		previewImport: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				content: string;
				format: "jspf" | "xspf" | "csv";
				jobId: string;
				filename?: string | undefined;
			};
			output: {
				collections: {
					name: string;
					type: "album" | "playlist";
					total: number;
					matched: number;
					unmatched: number;
					alreadyInLibrary: number;
					tracks: {
						title: string;
						artist: string;
						image: string | null;
						durationMs: number;
						matched: boolean;
						alreadyInLibrary: boolean;
						method: string;
					}[];
				}[];
			};
			meta: object;
		}>;
		commitImport: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				content: string;
				format: "jspf" | "xspf" | "csv";
				jobId: string;
				filename?: string | undefined;
				selection?: number[][] | undefined;
			};
			output: {
				attempted: number;
				imported: number;
				alreadyExisted: number;
				unmatchedTracks: number;
				failed: number;
			};
			meta: object;
		}>;
	}>>;
	settings: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		get: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				connections: {
					slskd: {
						apiUrl: string;
						apiKey: string;
						bannedUsers: string[];
					};
					plex: {
						url: string;
						token: string;
					};
					lidarr: {
						url: string;
						apiKey: string;
					};
					enrichment: {
						lastfmApiKey: string;
						fanartApiKey: string;
						songlinkApiKey: string;
						acoustidApiKey: string;
						musicbrainzEmail: string;
						discogsToken: string;
					};
					spotify: {
						enabled: boolean;
						clientId: string;
						publicBaseUrl: string;
					};
				};
				engine: {
					queue: {
						maxSize: number;
						maxConcurrentSearches: number;
						maxPendingImports: number;
					};
					search: {
						maxPeerAttempts: number;
						maxVariations: number;
						historyCleanupEnabled: boolean;
						maxHistorySearches: number;
						banAfterFailedAttempts: number;
					};
					timeouts: {
						searchPhase: number;
						downloadPhase: number;
						importPhase: number;
						peerUnresponsive: number;
						queueWaitActivePeer: number;
						queueWaitIdlePeer: number;
					};
					import: {
						metadataConfidenceThreshold: number;
					};
					plexBehavior: {
						libraryScan: boolean;
						playlistSync: boolean;
					};
					smartSearch: {
						customMoodKeywords: string[];
						federatedPatternsEnabled: boolean;
					};
				};
				formatting: {
					plexPlaylistUsernameAffix: "prefix" | "off" | "suffix";
					plexPlaylistUsernameSeparator: string;
				};
				library: {
					syncIntervalMinutes: number;
				};
				downloadSources: {
					slskd: {
						enabled: boolean;
						priority: number;
					};
					ytdlp: {
						enabled: boolean;
						priority: number;
						searchResults: number;
						maxDurationDeltaSec: number;
						searchTimeout: number;
					};
				};
				system: {
					wizardCompleted: boolean;
					migrationCompleted: boolean;
					instanceId: string;
					logLevel: "DEBUG" | "INFO" | "WARN" | "ERROR";
				};
			};
			meta: object;
		}>;
		getPublicConfig: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				publicBaseUrl: string;
				spotify: {
					enabled: boolean;
					configured: boolean;
				};
			};
			meta: object;
		}>;
		downloadSourcesAvailability: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				slskd: boolean;
				ytdlp: boolean;
			};
			meta: object;
		}>;
		updateConnectionsSlskd: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				apiUrl: string;
				apiKey: string;
				bannedUsers?: string[] | undefined;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateConnectionsPlex: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				url: string;
				token: string;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateConnectionsLidarr: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				url: string;
				apiKey: string;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateConnectionsEnrichment: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				lastfmApiKey: string;
				fanartApiKey: string;
				songlinkApiKey: string;
				acoustidApiKey: string;
				musicbrainzEmail: string;
				discogsToken?: string | undefined;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateConnectionsSpotify: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				clientId: string;
				publicBaseUrl: string;
				enabled?: boolean | undefined;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateLibrary: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				syncIntervalMinutes?: number | undefined;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateDownloadSources: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				slskd: {
					enabled?: boolean | undefined;
					priority?: number | undefined;
				};
				ytdlp: {
					enabled?: boolean | undefined;
					priority?: number | undefined;
					searchResults?: number | undefined;
					maxDurationDeltaSec?: number | undefined;
					searchTimeout?: number | undefined;
				};
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateSystemLogLevel: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				level: "DEBUG" | "INFO" | "WARN" | "ERROR";
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateEngineQueue: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				maxSize: number;
				maxConcurrentSearches: number;
				maxPendingImports: number;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateEngineSearch: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				maxPeerAttempts: number;
				maxVariations: number;
				historyCleanupEnabled: boolean;
				maxHistorySearches: number;
				banAfterFailedAttempts?: number | undefined;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateEngineTimeouts: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				downloadPhase: number;
				importPhase: number;
				peerUnresponsive: number;
				queueWaitActivePeer: number;
				queueWaitIdlePeer: number;
				searchPhase?: number | undefined;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateEngineImport: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				metadataConfidenceThreshold: number;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateEnginePlexBehavior: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				libraryScan: boolean;
				playlistSync: boolean;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateEngineSmartSearch: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				customMoodKeywords: string[];
				federatedPatternsEnabled: boolean;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		updateFormatting: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				plexPlaylistUsernameAffix: "prefix" | "off" | "suffix";
				plexPlaylistUsernameSeparator: string;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		testSlskd: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				apiUrl: string;
				apiKey: string;
			};
			output: {
				ok: boolean;
				message?: string | undefined;
			};
			meta: object;
		}>;
		testLidarr: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				url: string;
				apiKey: string;
			};
			output: {
				ok: boolean;
				message?: string | undefined;
			};
			meta: object;
		}>;
		plexConnectStart: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				pinId: string;
				authUrl: string;
			};
			meta: object;
		}>;
		plexConnectPoll: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				pinId: string;
			};
			output: {
				status: "pending";
			} | {
				status: "ready";
				token: string;
				servers: {
					name: string;
					clientIdentifier: string;
					uri: string;
					local: boolean;
				}[];
			};
			meta: object;
		}>;
		plexConnectSave: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				url: string;
				token: string;
			};
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		finishWizard: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				ok: boolean;
			};
			meta: object;
		}>;
		plexStatus: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				url: string;
				connected: boolean;
			};
			meta: object;
		}>;
		slskdStatus: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				configured: boolean;
				status: "healthy" | "unhealthy" | "not_configured";
				message?: string | undefined;
				messageCode?: "PLEX_NOT_CONFIGURED" | "PLEX_UNREACHABLE" | "LIDARR_CONNECTION_FAILED" | "ACOUSTID_NOT_CONFIGURED" | "ACOUSTID_FPCALC_MISSING" | "ACOUSTID_READY" | "BEETS_DISABLED" | "BEETS_CLI_MISSING" | "BEETS_AVAILABLE" | "LIDARR_NOT_CONFIGURED" | "LIDARR_CONNECTED" | "MUSIC_PROVIDER_UNAVAILABLE" | "MUSIC_PROVIDER_REACHABLE" | "MUSIC_PROVIDER_UNREACHABLE" | "PLEX_CONNECTED" | "PLEX_CONNECTED_NO_LIBRARY" | "SLSKD_NOT_CONFIGURED" | "SLSKD_API_ERROR" | "SLSKD_NETWORK_UNKNOWN" | "SLSKD_NETWORK_DISCONNECTED" | "SLSKD_CONNECTED" | "PATHS_ACCESSIBLE" | "DOWNLOADS_NOT_WRITABLE" | "LIBRARY_NOT_ACCESSIBLE" | "LIBRARY_READ_ONLY" | undefined;
				messageParams?: Record<string, string> | undefined;
			};
			meta: object;
		}>;
		lidarrStatus: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				configured: boolean;
				status: "healthy" | "unhealthy" | "not_configured";
				message?: string | undefined;
				messageCode?: "PLEX_NOT_CONFIGURED" | "PLEX_UNREACHABLE" | "LIDARR_CONNECTION_FAILED" | "ACOUSTID_NOT_CONFIGURED" | "ACOUSTID_FPCALC_MISSING" | "ACOUSTID_READY" | "BEETS_DISABLED" | "BEETS_CLI_MISSING" | "BEETS_AVAILABLE" | "LIDARR_NOT_CONFIGURED" | "LIDARR_CONNECTED" | "MUSIC_PROVIDER_UNAVAILABLE" | "MUSIC_PROVIDER_REACHABLE" | "MUSIC_PROVIDER_UNREACHABLE" | "PLEX_CONNECTED" | "PLEX_CONNECTED_NO_LIBRARY" | "SLSKD_NOT_CONFIGURED" | "SLSKD_API_ERROR" | "SLSKD_NETWORK_UNKNOWN" | "SLSKD_NETWORK_DISCONNECTED" | "SLSKD_CONNECTED" | "PATHS_ACCESSIBLE" | "DOWNLOADS_NOT_WRITABLE" | "LIBRARY_NOT_ACCESSIBLE" | "LIBRARY_READ_ONLY" | undefined;
				messageParams?: Record<string, string> | undefined;
			};
			meta: object;
		}>;
	}>>;
	subscriptionEvents: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		onEvent: import("@trpc/server").TRPCSubscriptionProcedure<{ input: unknown; output: SubscriptionEvent; meta: object }>;
	}>>;
	library: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		getTracks: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				limit?: number | undefined;
				offset?: number | undefined;
				q?: string | undefined;
				sort?: "artist" | "status" | "title" | "album" | "duration" | "recent" | "oldest" | undefined;
				direction?: "asc" | "desc" | undefined;
				filters?: {
					status?: ("queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated")[] | undefined;
					source?: string[] | undefined;
					format?: ("mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus")[] | undefined;
					artist?: string[] | undefined;
					albumId?: string[] | undefined;
					genre?: string[] | undefined;
					playlist?: string[] | undefined;
					requestedBy?: string[] | undefined;
					orphan?: boolean | undefined;
				} | undefined;
				facetSearch?: {
					artist?: string | undefined;
					genre?: string | undefined;
					playlist?: string | undefined;
					owner?: string | undefined;
				} | undefined;
			};
			output: {
				items: {
					id: string;
					external_id: string;
					title: string;
					artist: string;
					status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
					source: string;
					format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
					request_type: "artist" | "track" | "album" | "playlist";
					bitrate: number;
					duration_ms: number;
					track_number: number;
					disc_number: number;
					explicit: boolean;
					album_id: string;
					albumName: string;
					albumArt: string | null;
					genres: string[];
					playlistIds: string[];
					created_at: Date;
					completed_at: Date | null;
				}[];
				total: number;
				facets: Record<string, {
					value: string;
					label: string;
					count: number;
				}[]>;
			};
			meta: object;
		}>;
		getAlbums: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				limit?: number | undefined;
				offset?: number | undefined;
				q?: string | undefined;
				sort?: "name" | "artist" | "year" | "tracks" | "recent" | undefined;
				direction?: "asc" | "desc" | undefined;
				filters?: {
					status?: ("queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated")[] | undefined;
					artist?: string[] | undefined;
					genre?: string[] | undefined;
					year?: string[] | undefined;
					source?: string[] | undefined;
				} | undefined;
				facetSearch?: {
					artist?: string | undefined;
					genre?: string | undefined;
					playlist?: string | undefined;
					owner?: string | undefined;
				} | undefined;
			};
			output: {
				items: {
					id: string;
					external_id: string;
					name: string;
					artist: string;
					album_art: string | null;
					status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
					total_tracks: number;
					completed_tracks: number;
					source_provider: string | null;
					release_date: string;
					genres: string[];
					year: number | null;
					quality: string | null;
					requested: boolean;
					created_at: Date;
				}[];
				total: number;
				facets: Record<string, {
					value: string;
					label: string;
					count: number;
				}[]>;
			};
			meta: object;
		}>;
		getArtists: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				limit?: number | undefined;
				offset?: number | undefined;
				q?: string | undefined;
				sort?: "name" | "albums" | "tracks" | undefined;
				direction?: "asc" | "desc" | undefined;
				filters?: {
					genre?: string[] | undefined;
					source?: string[] | undefined;
					status?: ("queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated")[] | undefined;
				} | undefined;
				facetSearch?: {
					artist?: string | undefined;
					genre?: string | undefined;
					playlist?: string | undefined;
					owner?: string | undefined;
				} | undefined;
			};
			output: {
				items: {
					artist: string;
					trackCount: number;
					albumCount: number;
					albumArt: string | null;
					genre: string | null;
				}[];
				total: number;
				facets: Record<string, {
					value: string;
					label: string;
					count: number;
				}[]>;
			};
			meta: object;
		}>;
		getPlaylists: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				limit?: number | undefined;
				offset?: number | undefined;
				q?: string | undefined;
				sort?: "name" | "tracks" | "recent" | undefined;
				direction?: "asc" | "desc" | undefined;
				filters?: {
					source?: string[] | undefined;
					owner?: string[] | undefined;
					status?: ("queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated")[] | undefined;
				} | undefined;
				facetSearch?: {
					artist?: string | undefined;
					genre?: string | undefined;
					playlist?: string | undefined;
					owner?: string | undefined;
				} | undefined;
			};
			output: {
				items: {
					id: string;
					external_id: string;
					name: string;
					owner: string;
					image: string | null;
					images: string[];
					status: "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "complete" | "failed" | "cancelled" | "delegated";
					total_tracks: number;
					completed_tracks: number;
					source_provider: string | null;
					sync_enabled: boolean;
					created_at: Date;
				}[];
				total: number;
				facets: Record<string, {
					value: string;
					label: string;
					count: number;
				}[]>;
			};
			meta: object;
		}>;
		getCounts: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				tracks: number;
				albums: number;
				artists: number;
				playlists: number;
			};
			meta: object;
		}>;
	}>>;
	librarySource: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		spotify: import("@trpc/server").TRPCBuiltRouter<{
			ctx: Context;
			meta: object;
			errorShape: {
				data: {
					zodError: unknown | null;
					appCode: AppErrorCode | null;
					code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
					httpStatus: number;
					path?: string;
					stack?: string;
				};
				message: string;
				code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
			};
			transformer: true;
		}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
			getAuthUrl: import("@trpc/server").TRPCMutationProcedure<{
				input: void;
				output: {
					url: string;
				};
				meta: object;
			}>;
			handleCallback: import("@trpc/server").TRPCMutationProcedure<{
				input: {
					state: string;
					code: string;
				};
				output: {
					success: boolean;
				};
				meta: object;
			}>;
			disconnect: import("@trpc/server").TRPCMutationProcedure<{
				input: void;
				output: {
					success: boolean;
				};
				meta: object;
			}>;
			getConnectionStatus: import("@trpc/server").TRPCQueryProcedure<{
				input: void;
				output: {
					connected: boolean;
					pending: boolean;
					externalUsername: string | null;
					externalUserId: string | null;
					scopes: string[];
					expiresAt: Date | null;
				};
				meta: object;
			}>;
			listPlaylists: import("@trpc/server").TRPCQueryProcedure<{
				input: void;
				output: {
					id: string;
					name: string;
					description: string | null;
					owner: {
						id: string;
						name: string;
					};
					image: string | null;
					total_tracks: number;
					snapshot_id: string;
					collaborative: boolean;
					public: boolean;
					is_owner: boolean;
					already_imported: boolean;
				}[];
				meta: object;
			}>;
			listSavedAlbums: import("@trpc/server").TRPCQueryProcedure<{
				input: void;
				output: {
					id: string;
					name: string;
					artist: string;
					image: string | null;
					release_date: string;
					total_tracks: number;
					added_at: string;
					already_imported: boolean;
				}[];
				meta: object;
			}>;
			getLikedCount: import("@trpc/server").TRPCQueryProcedure<{
				input: void;
				output: {
					total: number;
					alreadyImported: boolean;
				};
				meta: object;
			}>;
			getTopTracks: import("@trpc/server").TRPCQueryProcedure<{
				input: {
					range: "short_term" | "medium_term" | "long_term";
					limit?: number | undefined;
				};
				output: {
					id: string;
					title: string;
					artist: string;
					album: string;
					image: string | null;
					duration_ms: number;
				}[];
				meta: object;
			}>;
			getTopArtists: import("@trpc/server").TRPCQueryProcedure<{
				input: {
					range: "short_term" | "medium_term" | "long_term";
					limit?: number | undefined;
				};
				output: {
					id: string;
					name: string;
					image: string | null;
					genres: string[];
					followers: number | null;
				}[];
				meta: object;
			}>;
			importSelection: import("@trpc/server").TRPCMutationProcedure<{
				input: {
					config: {
						bitrate: {
							value: number;
							matching: "strict" | "flexible";
						};
						format: {
							value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
							matching: "strict" | "flexible";
						};
						minUploadSpeed?: number | undefined;
						requireFreeSlot?: boolean | undefined;
						sourceChain?: ("slskd" | "ytdlp")[] | undefined;
					};
					playlistIds?: string[] | undefined;
					enableSyncForPlaylistIds?: string[] | undefined;
					importLikedSongs?: boolean | undefined;
					enableSyncLikedSongs?: boolean | undefined;
					savedAlbumIds?: string[] | undefined;
				};
				output: {
					playlists: {
						attempted: number;
						imported: number;
						alreadyExisted: number;
						unmatchedTracks: number;
						failed: number;
					};
					likedSongs: {
						attempted: number;
						imported: number;
						alreadyExisted: number;
						unmatchedTracks: number;
						failed: number;
					};
					savedAlbums: {
						attempted: number;
						imported: number;
						alreadyExisted: number;
						unmatchedTracks: number;
						failed: number;
					};
				};
				meta: object;
			}>;
			probeProfile: import("@trpc/server").TRPCMutationProcedure<{
				input: void;
				output: {
					status: "ok" | "still_restricted" | "no_connection";
					externalUsername?: string | null | undefined;
					externalUserId?: string | null | undefined;
					message?: string | undefined;
				};
				meta: object;
			}>;
			runSyncNow: import("@trpc/server").TRPCMutationProcedure<{
				input: void;
				output: {
					newPlaylists: number;
					updatedPlaylists: number;
					newSavedAlbums: number;
					errors: number;
				};
				meta: object;
			}>;
			syncPlaylistNow: import("@trpc/server").TRPCMutationProcedure<{
				input: {
					playlistId: string;
				};
				output: {
					status: "not_found" | "synced" | "no_change" | "not_synced_provider";
				};
				meta: object;
			}>;
			listLibraryItems: import("@trpc/server").TRPCQueryProcedure<{
				input: void;
				output: {
					id: string;
					type: "album" | "playlist" | "liked";
					name: string;
					subtitle: string | null;
					image: string | null;
					totalTracks: number;
					externalUrl: string;
					imported: boolean;
					syncEnabled: boolean;
					lastSyncedAt: Date | null;
					localId: string | null;
				}[];
				meta: object;
			}>;
			getLibraryItemDetail: import("@trpc/server").TRPCQueryProcedure<{
				input: {
					id: string;
					type: "album" | "playlist" | "liked";
				};
				output: {
					id: string;
					type: "album" | "playlist" | "liked";
					name: string;
					subtitle: string | null;
					image: string | null;
					totalTracks: number;
					externalUrl: string;
					crumb: string;
					released: string | null;
					label: string | null;
					sourceId: string;
					lastSyncedAt: Date | null;
					trackPreview: {
						position: number;
						title: string;
						artist: string;
						duration: string;
					}[];
					hasMore: boolean;
				};
				meta: object;
			}>;
			saveLibraryChanges: import("@trpc/server").TRPCMutationProcedure<{
				input: {
					jobId: string;
					config: {
						bitrate: {
							value: number;
							matching: "strict" | "flexible";
						};
						format: {
							value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
							matching: "strict" | "flexible";
						};
						minUploadSpeed?: number | undefined;
						requireFreeSlot?: boolean | undefined;
						sourceChain?: ("slskd" | "ytdlp")[] | undefined;
					};
					toImport?: {
						id: string;
						type: "album" | "playlist" | "liked";
						syncEnabled: boolean;
					}[] | undefined;
					toToggleSync?: {
						localId: string;
						syncEnabled: boolean;
					}[] | undefined;
					subscription?: {
						watch_new_playlists?: boolean | undefined;
						watch_saved_albums?: boolean | undefined;
					} | undefined;
				};
				output: {
					playlistsImported: number;
					likedSongsImported: boolean;
					savedAlbumsImported: number;
					unmatchedTracks: number;
					failed: number;
					syncToggled: number;
					subscriptionUpdated: boolean;
				};
				meta: object;
			}>;
		}>>;
		subscription: import("@trpc/server").TRPCBuiltRouter<{
			ctx: Context;
			meta: object;
			errorShape: {
				data: {
					zodError: unknown | null;
					appCode: AppErrorCode | null;
					code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
					httpStatus: number;
					path?: string;
					stack?: string;
				};
				message: string;
				code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
			};
			transformer: true;
		}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
			get: import("@trpc/server").TRPCQueryProcedure<{
				input: {
					provider?: "spotify" | undefined;
				} | undefined;
				output: {
					provider: "spotify";
					watch_new_playlists: boolean;
					watch_saved_albums: boolean;
					enabled_since: Date;
					last_checked_at: Date | null;
				} | null;
				meta: object;
			}>;
			update: import("@trpc/server").TRPCMutationProcedure<{
				input: {
					provider?: "spotify" | undefined;
					watch_new_playlists?: boolean | undefined;
					watch_saved_albums?: boolean | undefined;
				};
				output: {
					provider: "spotify";
					watch_new_playlists: boolean;
					watch_saved_albums: boolean;
					enabled_since: Date;
					last_checked_at: Date | null;
				};
				meta: object;
			}>;
		}>>;
	}>>;
	lidarr: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		available: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				available: boolean;
			};
			meta: object;
		}>;
		getProfiles: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				qualityProfiles: LidarrQualityProfile[];
				metadataProfiles: LidarrMetadataProfile[];
				rootFolders: LidarrRootFolder[];
				defaults: {
					qualityProfileId: number | undefined;
					metadataProfileId: number | undefined;
					rootFolderPath: string | undefined;
				};
			};
			meta: object;
		}>;
		listTags: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				[x: string]: unknown;
				id: number;
				label: string;
			}[];
			meta: object;
		}>;
		delegateArtist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				artistName: string;
				rootFolderPath: string;
				qualityProfileId: number;
				metadataProfileId: number;
				monitor: "missing" | "all" | "future" | "none";
				artistMbid?: string | undefined;
				tags?: string[] | undefined;
			};
			output: {
				ok: true;
				artistName: string;
			};
			meta: object;
		}>;
	}>>;
	discovery: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		getConfig: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: DiscoveryConfig;
			meta: object;
		}>;
		updateListenBrainz: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				enabled?: boolean | undefined;
				username?: string | null | undefined;
				selectedKinds?: ("cf-recommendations" | "weekly-exploration" | "weekly-jams" | "daily-jams")[] | undefined;
				autoRequest?: boolean | undefined;
				replaceExistingPlaylist?: boolean | undefined;
				playlistNames?: Partial<Record<"cf-recommendations" | "weekly-exploration" | "weekly-jams" | "daily-jams", string>> | undefined;
			};
			output: DiscoveryConfig;
			meta: object;
		}>;
		updateLastfm: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				enabled?: boolean | undefined;
				username?: string | null | undefined;
			};
			output: DiscoveryConfig;
			meta: object;
		}>;
		getFeed: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				integration: "listenbrainz" | "lastfm";
				kind: string;
			};
			output: FeedResult | {
				kind: "none";
			};
			meta: object;
		}>;
		getAllFeeds: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				integration: IntegrationKey;
				kind: string;
				result: FeedResult;
			}[];
			meta: object;
		}>;
		getAvailableKinds: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				listenbrainz: ("cf-recommendations" | "weekly-exploration" | "weekly-jams" | "daily-jams")[];
				lastfm: ("recent-tracks" | "top-tracks-overall")[];
			};
			meta: object;
		}>;
	}>>;
	jobs: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		list: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				id: "library-sync" | "discovery-sweep" | "pattern-sync";
				name: string;
				description: string;
				intervalMs: number;
				nextRun: Date | null;
				lastRun: Date | null;
				lastStatus: string | null;
			}[];
			meta: object;
		}>;
		trigger: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: "library-sync" | "discovery-sweep" | "pattern-sync";
			};
			output: {
				id: "library-sync" | "discovery-sweep" | "pattern-sync";
				status: "success";
				message: string;
			};
			meta: object;
		}>;
	}>>;
	logs: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		tail: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				lines?: number | undefined;
			};
			output: {
				file: string;
				entries: {
					raw: string;
					level: "DEBUG" | "INFO" | "WARN" | "ERROR" | "SUCCESS" | "ENGINE" | null;
					requestId: string | null;
				}[];
			};
			meta: object;
		}>;
	}>>;
	apiKeys: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		create: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				name: string;
			};
			output: {
				id: string;
				name: string;
				prefix: string;
				token: string;
				created_at: Date;
			};
			meta: object;
		}>;
		list: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				id: string;
				name: string;
				prefix: string;
				last_used_at: Date | null;
				created_at: Date;
			}[];
			meta: object;
		}>;
		revoke: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: string;
			};
			output: {
				success: boolean;
			};
			meta: object;
		}>;
	}>>;
	oauthConsent: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		getPending: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				grant: string;
			};
			output: {
				clientName: string;
				scopes: string[];
			};
			meta: object;
		}>;
		approve: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				grant: string;
			};
			output: {
				redirectUrl: string;
			};
			meta: object;
		}>;
		deny: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				grant: string;
			};
			output: {
				redirectUrl: string;
			};
			meta: object;
		}>;
	}>>;
	updates: import("@trpc/server").TRPCBuiltRouter<{
		ctx: Context;
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				appCode: AppErrorCode | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		current: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				currentVersion: string;
			};
			meta: object;
		}>;
		check: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				currentVersion: string;
				latestVersion: string | null;
				updateAvailable: boolean;
				checkedAt: Date;
			};
			meta: object;
		}>;
		patchNotes: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				schemaVersion: 1;
				versions: {
					version: string;
					date: string;
					type: "major" | "minor" | "patch";
					title: string;
					sections: {
						heading?: string | undefined;
						category?: "feature" | "fix" | "improvement" | "breaking" | "chore" | undefined;
						body?: string | undefined;
						items?: string[] | undefined;
					}[];
					callouts?: {
						level: "warning" | "important" | "note";
						body: string;
					}[] | undefined;
					issues?: number[] | undefined;
				}[];
			};
			meta: object;
		}>;
	}>>;
}>>;
export type AppRouter = typeof appRouter;