/**
 * Auto-generated types from Synthseek Backend
 * DO NOT EDIT - Generated by npm run generate
 * Generated at: 2026-04-19T18:15:25.880Z
 */

import { z } from "zod";

// ============================================================================
// ENUMS
// ============================================================================

export const RequestStatus = z.enum([
  "queued",
  "searching",
  "pending_download",
  "downloading",
  "paused",
  "pending_import",
  "importing",
  "in_progress",
  "syncing_plex",
  "partially_complete",
  "complete",
  "failed",
  "cancelled",
]);
export type RequestStatus = z.infer<typeof RequestStatus>;

export const ContentType = z.enum(["track", "album", "playlist", "artist"]);
export type ContentType = z.infer<typeof ContentType>;

export const SearchIntent = z.enum(["specific", "genre", "mood", "inconclusive"]);
export type SearchIntent = z.infer<typeof SearchIntent>;

export const RequestFormat = z.enum(["mp3", "flac", "aac", "m4a", "ogg", "wav", "opus"]);
export type RequestFormat = z.infer<typeof RequestFormat>;

export const RequestMatchingMode = z.enum(["strict", "flexible"]);
export type RequestMatchingMode = z.infer<typeof RequestMatchingMode>;

// ============================================================================
// SCHEMAS
// ============================================================================

export const AlbumSchema = z.object({
  id: z.string(),
  external_id: z.string(),
  name: z.string(),
  artist: z.string(),
  album_art: z.string().nullable(),
  user_id: z.string().nullable(),
  release_date: z.string(),
  total_tracks: z.number().int(),
  completed_tracks: z.number().int(),
  status: RequestStatus.default("queued"),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
});
export type Album = z.infer<typeof AlbumSchema>;

export const TrackRequestSchema = z.object({
  id: z.string(),
  slskd_request_id: z.string(),
  external_id: z.string(),
  user_id: z.string().nullable(),
  title: z.string(),
  artist: z.string(),
  request_type: ContentType.default("track"),
  isrc: z.string().nullable(),
  track_number: z.number().int(),
  disc_number: z.number().int().default(1),
  duration_ms: z.number().int(),
  status: RequestStatus.default("queued"),
  progress: z.number().int(),
  bitrate: z.number().int().default(320),
  format: RequestFormat.default("mp3"),
  format_matching: RequestMatchingMode.default("flexible"),
  bitrate_matching: RequestMatchingMode.default("flexible"),
  album_id: z.string(),
  error: z.string().nullable(),
  explicit: z.boolean(),
  source: z.string().default("deezer"),
  created_at: z.coerce.date(),
  completed_at: z.coerce.date().nullable(),
  updated_at: z.coerce.date(),
});
export type TrackRequest = z.infer<typeof TrackRequestSchema>;

// ============================================================================
// RELATION SCHEMAS
// ============================================================================

export const RequestWithTracksSchema = AlbumSchema.extend({
  tracks: z.array(TrackRequestSchema),
  contentType: ContentType,
  plex_playlist_id: z.string().nullable(),
});
export type RequestWithTracks = z.infer<typeof RequestWithTracksSchema>;

export const TrackRequestWithAlbumSchema = TrackRequestSchema.extend({
  Album: AlbumSchema,
});
export type TrackRequestWithAlbum = z.infer<typeof TrackRequestWithAlbumSchema>;

// ============================================================================
// SUBSCRIPTION EVENTS
// ============================================================================

export enum SubscriptionEventType {
  TrackUpdate = "TrackUpdate",
  AlbumUpdate = "AlbumUpdate",
  PlaylistUpdate = "PlaylistUpdate",
  PlaylistPlexCreated = "PlaylistPlexCreated",
  VersionUpdate = "VersionUpdate",
}

export interface TrackUpdatePayload {
  eventType: SubscriptionEventType.TrackUpdate;
  requestId: string;
  status: RequestStatus;
  progress?: number;
  error?: string;
  message: string;
  persisted?: boolean;
  metadata?: {
    artist?: string;
    track?: string;
    filename?: string;
    username?: string;
    id?: string;
  };
}

export interface AlbumUpdatePayload {
  eventType: SubscriptionEventType.AlbumUpdate;
  albumId: string;
  status: RequestStatus;
  completedTracks: number;
  totalTracks: number;
}

export interface PlaylistUpdatePayload {
  eventType: SubscriptionEventType.PlaylistUpdate;
  playlistId: string;
  status: RequestStatus;
  completedTracks: number;
  totalTracks: number;
}

export interface PlaylistPlexCreatedPayload {
  eventType: SubscriptionEventType.PlaylistPlexCreated;
  playlistId: string;
  plexPlaylistId: string;
}

export interface VersionUpdatePayload {
  eventType: SubscriptionEventType.VersionUpdate;
  currentVersion: string;
  latestVersion: string;
  message: string;
}

export type SubscriptionEvent =
  | TrackUpdatePayload
  | AlbumUpdatePayload
  | PlaylistUpdatePayload
  | PlaylistPlexCreatedPayload
  | VersionUpdatePayload;

// ============================================================================
// CONSTANTS
// ============================================================================

export const ACTIVE_STATUSES = [
  RequestStatus.enum.queued,
  RequestStatus.enum.in_progress,
  RequestStatus.enum.searching,
  RequestStatus.enum.pending_download,
  RequestStatus.enum.downloading,
  RequestStatus.enum.paused,
  RequestStatus.enum.pending_import,
  RequestStatus.enum.importing,
  RequestStatus.enum.syncing_plex,
] as const;

export const RESOLVED_STATUSES = [
  RequestStatus.enum.complete,
  RequestStatus.enum.partially_complete,
] as const;

export const UNRESOLVED_STATUSES = [
  RequestStatus.enum.failed,
  RequestStatus.enum.cancelled,
] as const;

export const FORMAT_OPTIONS = [
  { value: RequestFormat.enum.mp3, label: "MP3", desc: "Universal" },
  { value: RequestFormat.enum.flac, label: "FLAC", desc: "Lossless" },
  { value: RequestFormat.enum.aac, label: "AAC", desc: "High Quality" },
  { value: RequestFormat.enum.m4a, label: "M4A", desc: "Apple Lossless" },
  { value: RequestFormat.enum.ogg, label: "OGG", desc: "Open Source" },
  { value: RequestFormat.enum.wav, label: "WAV", desc: "Uncompressed" },
  { value: RequestFormat.enum.opus, label: "OPUS", desc: "Efficient Streaming" },
] as const;

// ============================================================================
// MUSIC TYPES (provider-agnostic)
// ============================================================================

export interface MusicImage {
  url: string;
  width: number | null;
  height: number | null;
}

export interface MusicArtistRef {
  id: string;
  name: string;
}

export interface MusicTrack {
  type: "track";
  id: string;
  title: string;
  artist: string;
  artists: MusicArtistRef[];
  album: { id: string; name: string; images: MusicImage[] };
  duration_ms: number;
  track_number: number;
  disc_number: number;
  isrc: string | null;
  explicit: boolean;
  popularity: number | null;
  preview_url: string | null;
  images: MusicImage[];
}

export interface MusicAlbum {
  type: "album";
  id: string;
  name: string;
  artist: string;
  artists: MusicArtistRef[];
  images: MusicImage[];
  release_date: string;
  total_tracks: number;
  genres: string[];
  label: string | null;
  upc: string | null;
  tracks: MusicTrack[];
}

export interface MusicArtist {
  type: "artist";
  id: string;
  name: string;
  images: MusicImage[];
  genres: string[];
  followers: number | null;
}

export interface MusicPlaylist {
  type: "playlist";
  id: string;
  name: string;
  description: string | null;
  images: MusicImage[];
  owner: { id: string; name: string };
  total_tracks: number;
  tracks: MusicPlaylistTrack[];
}

export interface MusicPlaylistTrack {
  added_at: string | null;
  track: MusicTrack;
}

export interface MusicGenre {
  id: string;
  name: string;
  images: MusicImage[];
}

export interface PagingResult<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

export type MusicItem = MusicTrack | MusicAlbum | MusicArtist | MusicPlaylist;

export interface SearchResults {
  tracks?: PagingResult<MusicTrack>;
  albums?: PagingResult<MusicAlbum>;
  artists?: PagingResult<MusicArtist>;
  playlists?: PagingResult<MusicPlaylist>;
}

export interface ClassificationResult {
  intent: SearchIntent;
  confidence: number;
  genreId?: string;
  genreName?: string;
  enrichTerms?: string[];
  source: "genre-rules" | "learned-pattern" | "post-search" | "llm" | "default";
}

export type FilterType = ContentType | "all";

export interface FilterTab {
  value: FilterType;
  label: string;
}

export interface TrendingResult {
  tracks: { track: MusicTrack; addedAt: string }[];
  source: { name: string; totalResults: number };
}


export interface ArtistSpotlightItem {
  artist: MusicArtist;
  latestAlbum: MusicAlbum | null;
}

export interface ArtistSpotlightResponse {
  artists: ArtistSpotlightItem[];
}

// ============================================================================
// SINGLE DOWNLOAD RESULT
// ============================================================================

export interface SingleDownloadResult {
  success: boolean;
  request: TrackRequest;
  album: Album;
}


// ============================================================================
// TRPC ROUTER TYPE (auto-generated from tsc declaration output)
// ============================================================================

export declare const appRouter: import("@trpc/server").TRPCBuiltRouter<{
	ctx: {
		prisma: unknown;
		logger: unknown;
		headers: Headers;
	};
	meta: object;
	errorShape: {
		data: {
			zodError: unknown | null;
			code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
			httpStatus: number;
			path?: string;
			stack?: string;
		};
		message: string;
		code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
	};
	transformer: true;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
	requests: import("@trpc/server").TRPCBuiltRouter<{
		ctx: {
			prisma: unknown;
			logger: unknown;
			headers: Headers;
		};
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		request: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				track: {
					explicit: boolean;
					external_id: string;
					artist: string;
					title: string;
					isrc: string | null;
					track_number: number;
					duration_ms: number;
					disc_number?: number | undefined;
				};
				config: {
					bitrate: {
						value: number;
						matching: "strict" | "flexible";
					};
					format: {
						value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
						matching: "strict" | "flexible";
					};
				};
				album_external_id: string;
			};
			output: SingleDownloadResult;
			meta: object;
		}>;
		batchRequest: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				name: string;
				external_id: string;
				artist: string;
				album_art: string | null;
				release_date: string;
				total_tracks: number;
				tracks: {
					explicit: boolean;
					external_id: string;
					artist: string;
					title: string;
					isrc: string | null;
					track_number: number;
					duration_ms: number;
					disc_number?: number | undefined;
				}[];
				config: {
					bitrate: {
						value: number;
						matching: "strict" | "flexible";
					};
					format: {
						value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
						matching: "strict" | "flexible";
					};
				};
			};
			output: {
				id: string;
				external_id: string;
				name: string;
				artist: string;
				album_art: string | null;
				user_id: string | null;
				release_date: string;
				total_tracks: number;
				completed_tracks: number;
				status: "complete" | "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "failed" | "cancelled";
				created_at: Date;
				updated_at: Date;
				tracks: {
					id: string;
					slskd_request_id: string;
					external_id: string;
					user_id: string | null;
					title: string;
					artist: string;
					request_type: "album" | "artist" | "track" | "playlist";
					isrc: string | null;
					track_number: number;
					disc_number: number;
					duration_ms: number;
					status: "complete" | "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "failed" | "cancelled";
					progress: number;
					bitrate: number;
					format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
					format_matching: "strict" | "flexible";
					bitrate_matching: "strict" | "flexible";
					album_id: string;
					error: string | null;
					explicit: boolean;
					source: string;
					created_at: Date;
					completed_at: Date | null;
					updated_at: Date;
				}[];
				contentType: "album" | "artist" | "track" | "playlist";
				plex_playlist_id: string | null;
			};
			meta: object;
		}>;
		getStatus: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				requestId: string;
			};
			output: {
				success: boolean;
				status: {
					requestId: string;
					status: RequestStatus;
					progress: number;
					error: string | null;
				};
			};
			meta: object;
		}>;
		getAll: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				id: string;
				external_id: string;
				name: string;
				artist: string;
				album_art: string | null;
				user_id: string | null;
				release_date: string;
				total_tracks: number;
				completed_tracks: number;
				status: "complete" | "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "failed" | "cancelled";
				created_at: Date;
				updated_at: Date;
				tracks: {
					id: string;
					slskd_request_id: string;
					external_id: string;
					user_id: string | null;
					title: string;
					artist: string;
					request_type: "album" | "artist" | "track" | "playlist";
					isrc: string | null;
					track_number: number;
					disc_number: number;
					duration_ms: number;
					status: "complete" | "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "failed" | "cancelled";
					progress: number;
					bitrate: number;
					format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
					format_matching: "strict" | "flexible";
					bitrate_matching: "strict" | "flexible";
					album_id: string;
					error: string | null;
					explicit: boolean;
					source: string;
					created_at: Date;
					completed_at: Date | null;
					updated_at: Date;
				}[];
				contentType: "album" | "artist" | "track" | "playlist";
				plex_playlist_id: string | null;
			}[];
			meta: object;
		}>;
		createTrack: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				error: string | null;
				explicit: boolean;
				external_id: string;
				artist: string;
				user_id: string | null;
				created_at: Date;
				updated_at: Date;
				slskd_request_id: string;
				title: string;
				isrc: string | null;
				track_number: number;
				duration_ms: number;
				progress: number;
				album_id: string;
				completed_at: Date | null;
				format?: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus" | undefined;
				status?: "complete" | "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "failed" | "cancelled" | undefined;
				disc_number?: number | undefined;
				bitrate?: number | undefined;
				format_matching?: "strict" | "flexible" | undefined;
				bitrate_matching?: "strict" | "flexible" | undefined;
				source?: string | undefined;
			};
			output: {
				id: string;
				slskd_request_id: string;
				external_id: string;
				user_id: string | null;
				title: string;
				artist: string;
				request_type: "album" | "artist" | "track" | "playlist";
				isrc: string | null;
				track_number: number;
				disc_number: number;
				duration_ms: number;
				status: "complete" | "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "failed" | "cancelled";
				progress: number;
				bitrate: number;
				format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
				format_matching: "strict" | "flexible";
				bitrate_matching: "strict" | "flexible";
				album_id: string;
				error: string | null;
				explicit: boolean;
				source: string;
				created_at: Date;
				completed_at: Date | null;
				updated_at: Date;
			};
			meta: object;
		}>;
		update: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: string;
				status: "complete" | "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "failed" | "cancelled";
				progress?: number | undefined;
				error?: string | null | undefined;
				metadata?: Record<string, unknown> | undefined;
			};
			output: {
				id: string;
				slskd_request_id: string;
				external_id: string;
				user_id: string | null;
				title: string;
				artist: string;
				request_type: "album" | "artist" | "track" | "playlist";
				isrc: string | null;
				track_number: number;
				disc_number: number;
				duration_ms: number;
				status: "complete" | "queued" | "searching" | "pending_download" | "downloading" | "paused" | "pending_import" | "importing" | "in_progress" | "syncing_plex" | "partially_complete" | "failed" | "cancelled";
				progress: number;
				bitrate: number;
				format: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
				format_matching: "strict" | "flexible";
				bitrate_matching: "strict" | "flexible";
				album_id: string;
				error: string | null;
				explicit: boolean;
				source: string;
				created_at: Date;
				completed_at: Date | null;
				updated_at: Date;
			};
			meta: object;
		}>;
		delete: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				id: string;
			};
			output: {
				success: boolean;
				id?: string | undefined;
			};
			meta: object;
		}>;
		deleteAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				success: boolean;
				id?: string | undefined;
			};
			meta: object;
		}>;
		retryAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				message: string;
				retriedCount: number;
			};
			meta: object;
		}>;
		cancelAlbum: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				albumId: string;
			};
			output: {
				message: string;
				cancelledCount: number;
			};
			meta: object;
		}>;
		cancelTrack: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				trackId: string;
			};
			output: {
				success: boolean;
				trackId: string;
			};
			meta: object;
		}>;
		retryTrack: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				trackId: string;
			};
			output: {
				success: boolean;
				trackId: string;
			};
			meta: object;
		}>;
		retryAllFailed: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				retried: number;
				failed: number;
			};
			meta: object;
		}>;
		deleteAll: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				deleted: number;
			};
			meta: object;
		}>;
		clearCompleted: import("@trpc/server").TRPCMutationProcedure<{
			input: void;
			output: {
				count: number;
			};
			meta: object;
		}>;
		getLibrarySummary: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				completedTracks: number;
				completedAlbums: number;
				queuedTracks: number;
				totalDurationMs: number;
				topArtists: {
					artist: string;
					trackCount: number;
				}[];
			};
			meta: object;
		}>;
		playlistRequest: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				external_id: string;
				name: string;
				owner: string;
				total_tracks: number;
				tracks: {
					explicit: boolean;
					external_id: string;
					artist: string;
					title: string;
					isrc: string | null;
					track_number: number;
					duration_ms: number;
					album_external_id: string;
					album_name: string;
					album_artist: string;
					disc_number?: number | undefined;
					album_image?: string | null | undefined;
				}[];
				config: {
					bitrate: {
						value: number;
						matching: "strict" | "flexible";
					};
					format: {
						value: "mp3" | "flac" | "m4a" | "ogg" | "aac" | "wav" | "opus";
						matching: "strict" | "flexible";
					};
				};
				description?: string | null | undefined;
				image?: string | null | undefined;
			};
			output: {
				success: boolean;
				data: {
					name: string;
					id: string;
					external_id: string;
					total_tracks: number;
					completed_tracks: number;
					status: RequestStatus;
					created_at: Date;
					updated_at: Date;
					description: string | null;
					owner: string;
					image: string | null;
					plex_playlist_id: string | null;
				} | null;
			};
			meta: object;
		}>;
		deletePlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				success: boolean;
			};
			meta: object;
		}>;
		retryPlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				retriedCount: number;
			};
			meta: object;
		}>;
		cancelPlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				cancelledCount: number;
			};
			meta: object;
		}>;
		retryPlexPlaylist: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				playlistId: string;
			};
			output: {
				success: boolean;
			};
			meta: object;
		}>;
	}>>;
	music: import("@trpc/server").TRPCBuiltRouter<{
		ctx: {
			prisma: unknown;
			logger: unknown;
			headers: Headers;
		};
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		search: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				q: string;
				type?: string | undefined;
				limit?: number | undefined;
				offset?: number | undefined;
			};
			output: {
				success: boolean;
				results: SearchResults;
				classification: ClassificationResult;
			};
			meta: object;
		}>;
		getContent: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				type: "album" | "artist" | "track" | "playlist";
				id: string;
				include?: ("album" | "artist" | "track" | "playlist")[] | undefined;
			};
			output: {
				success: boolean;
				data: Record<string, unknown>;
			};
			meta: object;
		}>;
		getContents: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				parentType: "album" | "artist" | "track" | "playlist";
				parentId: string;
			};
			output: {
				success: boolean;
				content: MusicTrack[] | MusicPlaylistTrack[] | MusicAlbum[];
			};
			meta: object;
		}>;
		getTrendingTracks: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				success: boolean;
				data: TrendingResult;
			};
			meta: object;
		}>;
		getArtistSpotlight: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				countryName: string;
				limit?: number | undefined;
			};
			output: {
				success: boolean;
				data: {
					artists: ArtistSpotlightItem[];
				};
			};
			meta: object;
		}>;
		getArtistTopTracks: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				artistId: string;
				limit?: number | undefined;
			};
			output: {
				success: boolean;
				data: MusicTrack[];
			};
			meta: object;
		}>;
		getCategories: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				limit?: number | undefined;
				offset?: number | undefined;
			};
			output: {
				success: boolean;
				data: {
					items: MusicGenre[];
					total: number;
					limit: number;
					offset: number;
				};
			};
			meta: object;
		}>;
		getCategoryPlaylists: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				categoryId: string;
				categoryName: string;
				limit?: number | undefined;
				offset?: number | undefined;
			};
			output: {
				success: boolean;
				data: GenreContent;
			};
			meta: object;
		}>;
		getSimilarArtists: import("@trpc/server").TRPCQueryProcedure<{
			input: {
				artistName: string;
				limit?: number | undefined;
			};
			output: {
				success: boolean;
				data: {
					id: string;
					name: string;
					match: number;
				}[];
			};
			meta: object;
		}>;
		importPlaylistFromUrl: import("@trpc/server").TRPCMutationProcedure<{
			input: {
				url: string;
			};
			output: {
				success: boolean;
				data: ResolvedTrack[];
			};
			meta: object;
		}>;
		detectCountry: import("@trpc/server").TRPCQueryProcedure<{
			input: void;
			output: {
				success: boolean;
				country: string;
			};
			meta: object;
		}>;
	}>>;
	subscriptionEvents: import("@trpc/server").TRPCBuiltRouter<{
		ctx: {
			prisma: unknown;
			logger: unknown;
			headers: Headers;
		};
		meta: object;
		errorShape: {
			data: {
				zodError: unknown | null;
				code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
				httpStatus: number;
				path?: string;
				stack?: string;
			};
			message: string;
			code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
		};
		transformer: true;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		onEvent: import("@trpc/server").TRPCSubscriptionProcedure<{ input: unknown; output: SubscriptionEvent; meta: object }>;
	}>>;
}>>;
export type AppRouter = typeof appRouter;