import type { PlayerDeviceKind, PlayerTrack } from "@components/Player";

import type { DemoDeviceId } from "./types";

export const DEMO_TRACKS: readonly PlayerTrack[] = [
  {
    id: "demo-1",
    title: "Bleeding Love (Radio Edit)",
    artist: "Leona Lewis",
    album: "Bleeding Love",
    durationSeconds: 239,
    format: "mp3",
    bitrateKbps: 320,
    lossless: false,
    tone: "primary",
    missing: false,
  },
  {
    id: "demo-2",
    title: "Svarta Tjärn",
    artist: "Fejd",
    album: "Nifelheim",
    durationSeconds: 317,
    format: "flac",
    bitrateKbps: 1411,
    lossless: true,
    tone: "secondary",
    missing: false,
  },
  {
    id: "demo-3",
    title: "Strilja",
    artist: "Fejd",
    album: "Nifelheim",
    durationSeconds: 301,
    format: "flac",
    bitrateKbps: 1411,
    lossless: true,
    tone: "secondary",
    missing: false,
  },
  {
    id: "demo-4",
    title: "Einar Blå",
    artist: "Fejd",
    album: "Nifelheim",
    durationSeconds: 303,
    format: "flac",
    bitrateKbps: 1411,
    lossless: true,
    tone: "secondary",
    missing: false,
  },
  {
    id: "demo-5",
    title: "Älvagrimmar",
    artist: "Fejd",
    album: "Nifelheim",
    durationSeconds: 376,
    format: "flac",
    bitrateKbps: 1411,
    lossless: true,
    tone: "secondary",
    missing: false,
  },
  {
    id: "demo-6",
    title: "Edsvuren",
    artist: "Fejd",
    album: "Nifelheim",
    durationSeconds: 318,
    format: "flac",
    bitrateKbps: 1411,
    lossless: true,
    tone: "secondary",
    missing: false,
  },
  {
    id: "demo-7",
    title: "Nidhögg",
    artist: "Fejd",
    album: "Nifelheim",
    durationSeconds: 447,
    format: "flac",
    bitrateKbps: 1411,
    lossless: true,
    tone: "secondary",
    missing: false,
  },
  {
    id: "demo-8",
    title: "Nifelheim",
    artist: "Fejd",
    album: "Nifelheim",
    durationSeconds: 247,
    format: "flac",
    bitrateKbps: 1411,
    lossless: true,
    tone: "secondary",
    missing: false,
  },
  {
    id: "demo-9",
    title: "Reach Us",
    artist: "Tech N9ne",
    album: "BLISS",
    durationSeconds: 205,
    format: "mp3",
    bitrateKbps: 320,
    lossless: false,
    tone: "accent",
    missing: false,
  },
  {
    id: "demo-10",
    title: "Dust In The Wind (Live)",
    artist: "Kansas",
    album: "Kansas - Live (Live)",
    durationSeconds: 290,
    format: "mp3",
    bitrateKbps: 320,
    lossless: false,
    tone: "primary",
    missing: true,
  },
  {
    id: "demo-11",
    title: "Nothing's Gonna Stop Us Now",
    artist: "Starship",
    album: "Greatest Hits",
    durationSeconds: 270,
    format: "mp3",
    bitrateKbps: 256,
    lossless: false,
    tone: "primary",
    missing: false,
  },
  {
    id: "demo-12",
    title: "MUCHAS GRACIAS ;*",
    artist: "Tito Double P",
    album: "ACOMODO",
    durationSeconds: 207,
    format: "mp3",
    bitrateKbps: 320,
    lossless: false,
    tone: "accent",
    missing: false,
  },
  {
    id: "demo-13",
    title: "YAMAME",
    artist: "Tito Double P",
    album: "ACOMODO",
    durationSeconds: 162,
    format: "mp3",
    bitrateKbps: 320,
    lossless: false,
    tone: "accent",
    missing: false,
  },
  {
    id: "demo-14",
    title: "TATTOO",
    artist: "Tito Double P",
    album: "TATTOO",
    durationSeconds: 167,
    format: "flac",
    bitrateKbps: 1411,
    lossless: true,
    tone: "primary",
    missing: false,
  },
  {
    id: "demo-15",
    title: "GUERITA Y MORENA",
    artist: "Tito Double P",
    album: "ACOMODO",
    durationSeconds: 159,
    format: "mp3",
    bitrateKbps: 320,
    lossless: false,
    tone: "accent",
    missing: false,
  },
  {
    id: "demo-16",
    title: "CRIPTONITA",
    artist: "Tito Double P",
    album: "CRIPTONITA",
    durationSeconds: 208,
    format: "mp3",
    bitrateKbps: 320,
    lossless: false,
    tone: "secondary",
    missing: false,
  },
];

export const DEMO_DEVICE_SEEDS: readonly { id: DemoDeviceId; kind: PlayerDeviceKind; local: boolean }[] = [
  { id: "here", kind: "own", local: true },
  { id: "desktop", kind: "own", local: false },
  { id: "phone", kind: "third", local: false },
  { id: "laptop", kind: "unarmed", local: false },
];

export const DEMO_INITIAL_QUEUE = ["demo-3", "demo-4", "demo-12", "demo-5", "demo-6", "demo-7", "demo-8"];

export const DEMO_NORMALIZATION_GAIN = "-6.4";

export const TICK_MS = 250;

export const LOADING_MS = 850;

export const NOTICE_MS = 4200;

export const SKIP_DELAY_MS = 900;
