// AUTO-GENERATED by scripts/gen-i18n.mjs. DO NOT EDIT (run `npm run gen:i18n`).
import "i18next";

import appShell from "./messages/en/appShell.json";
import auth from "./messages/en/auth.json";
import common from "./messages/en/common.json";
import components from "./messages/en/components.json";
import countries from "./messages/en/countries.json";
import discover from "./messages/en/discover.json";
import errors from "./messages/en/errors.json";
import health from "./messages/en/health.json";
import library from "./messages/en/library.json";
import mutations from "./messages/en/mutations.json";
import requests from "./messages/en/requests.json";
import search from "./messages/en/search.json";
import settings from "./messages/en/settings.json";
import setup from "./messages/en/setup.json";
import status from "./messages/en/status.json";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "common";
    resources: {
      appShell: typeof appShell;
      auth: typeof auth;
      common: typeof common;
      components: typeof components;
      countries: typeof countries;
      discover: typeof discover;
      errors: typeof errors;
      health: typeof health;
      library: typeof library;
      mutations: typeof mutations;
      requests: typeof requests;
      search: typeof search;
      settings: typeof settings;
      setup: typeof setup;
      status: typeof status;
    };
  }
}
