// AUTO-GENERATED by scripts/gen-i18n.mjs. DO NOT EDIT (run `npm run gen:i18n`).
import de_appShell from "./messages/de/appShell.json";
import de_auth from "./messages/de/auth.json";
import de_common from "./messages/de/common.json";
import de_components from "./messages/de/components.json";
import de_contentDetail from "./messages/de/contentDetail.json";
import de_countries from "./messages/de/countries.json";
import de_discover from "./messages/de/discover.json";
import de_errors from "./messages/de/errors.json";
import de_health from "./messages/de/health.json";
import de_library from "./messages/de/library.json";
import de_mutations from "./messages/de/mutations.json";
import de_player from "./messages/de/player.json";
import de_requests from "./messages/de/requests.json";
import de_search from "./messages/de/search.json";
import de_settings from "./messages/de/settings.json";
import de_setup from "./messages/de/setup.json";
import de_status from "./messages/de/status.json";
import en_appShell from "./messages/en/appShell.json";
import en_auth from "./messages/en/auth.json";
import en_common from "./messages/en/common.json";
import en_components from "./messages/en/components.json";
import en_contentDetail from "./messages/en/contentDetail.json";
import en_countries from "./messages/en/countries.json";
import en_discover from "./messages/en/discover.json";
import en_errors from "./messages/en/errors.json";
import en_health from "./messages/en/health.json";
import en_library from "./messages/en/library.json";
import en_mutations from "./messages/en/mutations.json";
import en_player from "./messages/en/player.json";
import en_requests from "./messages/en/requests.json";
import en_search from "./messages/en/search.json";
import en_settings from "./messages/en/settings.json";
import en_setup from "./messages/en/setup.json";
import en_status from "./messages/en/status.json";
import es_appShell from "./messages/es/appShell.json";
import es_auth from "./messages/es/auth.json";
import es_common from "./messages/es/common.json";
import es_components from "./messages/es/components.json";
import es_contentDetail from "./messages/es/contentDetail.json";
import es_countries from "./messages/es/countries.json";
import es_discover from "./messages/es/discover.json";
import es_errors from "./messages/es/errors.json";
import es_health from "./messages/es/health.json";
import es_library from "./messages/es/library.json";
import es_mutations from "./messages/es/mutations.json";
import es_player from "./messages/es/player.json";
import es_requests from "./messages/es/requests.json";
import es_search from "./messages/es/search.json";
import es_settings from "./messages/es/settings.json";
import es_setup from "./messages/es/setup.json";
import es_status from "./messages/es/status.json";
import fr_appShell from "./messages/fr/appShell.json";
import fr_auth from "./messages/fr/auth.json";
import fr_common from "./messages/fr/common.json";
import fr_components from "./messages/fr/components.json";
import fr_contentDetail from "./messages/fr/contentDetail.json";
import fr_countries from "./messages/fr/countries.json";
import fr_discover from "./messages/fr/discover.json";
import fr_errors from "./messages/fr/errors.json";
import fr_health from "./messages/fr/health.json";
import fr_library from "./messages/fr/library.json";
import fr_mutations from "./messages/fr/mutations.json";
import fr_player from "./messages/fr/player.json";
import fr_requests from "./messages/fr/requests.json";
import fr_search from "./messages/fr/search.json";
import fr_settings from "./messages/fr/settings.json";
import fr_setup from "./messages/fr/setup.json";
import fr_status from "./messages/fr/status.json";

export const resources = {
  de: {
    appShell: de_appShell,
    auth: de_auth,
    common: de_common,
    components: de_components,
    contentDetail: de_contentDetail,
    countries: de_countries,
    discover: de_discover,
    errors: de_errors,
    health: de_health,
    library: de_library,
    mutations: de_mutations,
    player: de_player,
    requests: de_requests,
    search: de_search,
    settings: de_settings,
    setup: de_setup,
    status: de_status,
  },
  en: {
    appShell: en_appShell,
    auth: en_auth,
    common: en_common,
    components: en_components,
    contentDetail: en_contentDetail,
    countries: en_countries,
    discover: en_discover,
    errors: en_errors,
    health: en_health,
    library: en_library,
    mutations: en_mutations,
    player: en_player,
    requests: en_requests,
    search: en_search,
    settings: en_settings,
    setup: en_setup,
    status: en_status,
  },
  es: {
    appShell: es_appShell,
    auth: es_auth,
    common: es_common,
    components: es_components,
    contentDetail: es_contentDetail,
    countries: es_countries,
    discover: es_discover,
    errors: es_errors,
    health: es_health,
    library: es_library,
    mutations: es_mutations,
    player: es_player,
    requests: es_requests,
    search: es_search,
    settings: es_settings,
    setup: es_setup,
    status: es_status,
  },
  fr: {
    appShell: fr_appShell,
    auth: fr_auth,
    common: fr_common,
    components: fr_components,
    contentDetail: fr_contentDetail,
    countries: fr_countries,
    discover: fr_discover,
    errors: fr_errors,
    health: fr_health,
    library: fr_library,
    mutations: fr_mutations,
    player: fr_player,
    requests: fr_requests,
    search: fr_search,
    settings: fr_settings,
    setup: fr_setup,
    status: fr_status,
  },
};
