// AUTO-GENERATED by scripts/gen-i18n.mjs. DO NOT EDIT (run `npm run gen:i18n`).
import en_appShell from "./messages/en/appShell.json";
import en_auth from "./messages/en/auth.json";
import en_common from "./messages/en/common.json";
import en_components from "./messages/en/components.json";
import en_contentDetail from "./messages/en/contentDetail.json";
import en_countries from "./messages/en/countries.json";
import en_discover from "./messages/en/discover.json";
import en_errors from "./messages/en/errors.json";
import en_health from "./messages/en/health.json";
import en_library from "./messages/en/library.json";
import en_mutations from "./messages/en/mutations.json";
import en_requests from "./messages/en/requests.json";
import en_search from "./messages/en/search.json";
import en_settings from "./messages/en/settings.json";
import en_setup from "./messages/en/setup.json";
import en_status from "./messages/en/status.json";
import es_appShell from "./messages/es/appShell.json";
import es_auth from "./messages/es/auth.json";
import es_common from "./messages/es/common.json";
import es_components from "./messages/es/components.json";
import es_contentDetail from "./messages/es/contentDetail.json";
import es_countries from "./messages/es/countries.json";
import es_discover from "./messages/es/discover.json";
import es_errors from "./messages/es/errors.json";
import es_health from "./messages/es/health.json";
import es_library from "./messages/es/library.json";
import es_mutations from "./messages/es/mutations.json";
import es_requests from "./messages/es/requests.json";
import es_search from "./messages/es/search.json";
import es_settings from "./messages/es/settings.json";
import es_setup from "./messages/es/setup.json";
import es_status from "./messages/es/status.json";

export const resources = {
  en: {
    appShell: en_appShell,
    auth: en_auth,
    common: en_common,
    components: en_components,
    contentDetail: en_contentDetail,
    countries: en_countries,
    discover: en_discover,
    errors: en_errors,
    health: en_health,
    library: en_library,
    mutations: en_mutations,
    requests: en_requests,
    search: en_search,
    settings: en_settings,
    setup: en_setup,
    status: en_status,
  },
  es: {
    appShell: es_appShell,
    auth: es_auth,
    common: es_common,
    components: es_components,
    contentDetail: es_contentDetail,
    countries: es_countries,
    discover: es_discover,
    errors: es_errors,
    health: es_health,
    library: es_library,
    mutations: es_mutations,
    requests: es_requests,
    search: es_search,
    settings: es_settings,
    setup: es_setup,
    status: es_status,
  },
};
